//! `template` — generate OWL from a template table (TSV/CSV).
//!
//! Row 1 holds human-readable headers; row 2 holds template strings; rows 3+
//! hold data. Cells that name a class expression are full Manchester syntax and
//! may reference entities by rdfs:label (single-quoted `'foo bar'` or a bare
//! token), CURIE (`OBO:1234`), or full IRI (`<...>`), resolved against a
//! label→IRI index built from the input ontology plus the template's own rows.
//!
//! The template strings owlmake implements. Real templates carry headers beyond
//! this list; one that is not here is unimplemented, and it emits nothing rather
//! than failing — so a component that comes out short is the first sign of it:
//!   `ID`                       the subject IRI (CURIE/IRI/label expanded)
//!   `LABEL`                    rdfs:label; also indexes the subject by label
//!   `TYPE` / `CLASS_TYPE` /    the subject's entity kind (class | object
//!     `PROPERTY_TYPE` /          property | data property | named individual |
//!     `INDIVIDUAL_TYPE`          datatype). Default: class.
//!   class axioms:  `C`/`SC` SubClassOf, `EC` EquivalentTo, `DC` DisjointWith
//!   property axioms: `SP` sub-, `EP` equivalent-, `DP` disjoint-property,
//!                    `DOMAIN`, `RANGE`, `IP` inverse property
//!   characteristics: `CHARACTERISTIC` (functional/transitive/symmetric/...)
//!   individual axioms: `I`/`TI` type (class assertion), `SI` same, `DI` different
//!   annotations: `A <prop>` literal, `AT <prop>^^<dt>` typed,
//!                `AL <prop>@<lang>` language-tagged, `AI <prop>` IRI value
//!   axiom annotations: a header beginning `>` (e.g. `>A <prop>`) annotates the
//!                      axiom generated by the immediately preceding column.
//!   trailing `SPLIT=<c>`       split the cell on `<c>` and apply once per value

use std::collections::HashMap;
use std::path::PathBuf;

use anyhow::bail;
use clap::Args as ClapArgs;
use horned_owl::model::{
    AnnotatedComponent, Annotation, AnnotationAssertion, AnnotationSubject, AnnotationValue, Build,
    ClassExpression as CE, Component, DeclareAnnotationProperty, DeclareClass,
    DeclareDataProperty, DeclareDatatype, DeclareNamedIndividual, DeclareObjectProperty,
    DisjointClasses, DisjointObjectProperties, EquivalentClasses, EquivalentObjectProperties,
    Individual, Literal, MutableOntology, ObjectPropertyExpression as OPE, RcStr, SubClassOf,
    SubObjectPropertyOf,
};
use horned_owl::ontology::set::SetOntology;

use crate::cmd::select;
use crate::io;
use crate::io::manchester_parse;
use crate::model::{default_prefixes, Model};

const RDFS_LABEL: &str = "http://www.w3.org/2000/01/rdf-schema#label";

#[derive(ClapArgs)]
pub struct Args {
    /// Template table(s) (.tsv or.csv). Repeatable; all tables are applied
    /// into the same output ontology.
    #[arg(short = 't', long = "template", value_name = "FILE")]
    pub template: Vec<PathBuf>,
    /// Optional input ontology to merge the generated axioms into.
    #[arg(short, long)]
    pub input: Option<PathBuf>,
    #[arg(short, long)]
    pub output: Option<PathBuf>,
    /// Output format. Long-only: `-f` is taken by `--force` on `template`.
    #[arg(long)]
    pub format: Option<String>,

    /// If true, log template errors and continue instead of aborting.
    /// `<bool>`.
    #[arg(short = 'f', long, num_args = 1, default_missing_value = "true")]
    pub force: Option<bool>,

    /// Write template errors to this file (TSV or CSV).
    #[arg(short = 'e', long, value_name = "FILE")]
    pub errors: Option<PathBuf>,

    /// Additional template file(s), treated exactly like `--template`.
    #[arg(short = 'E', long = "external-template", value_name = "FILE")]
    pub external_template: Vec<PathBuf>,

    /// Set the output ontology IRI.
    #[arg(short = 'O', long, value_name = "IRI")]
    pub ontology_iri: Option<String>,
    /// Set the output version IRI.
    #[arg(short = 'V', long, value_name = "IRI")]
    pub version_iri: Option<String>,

    /// Merge the generated axioms into the input ontology before output.
    /// owlmake already merges into the input when one is present; this forces
    /// that behavior on. `<bool>`.
    #[arg(short = 'm', long, num_args = 1, default_missing_value = "true")]
    pub merge_before: Option<bool>,
    /// Merge the generated axioms into the input ontology after output. Treated
    /// like `--merge-before` here. `<bool>`.
    #[arg(short = 'M', long, num_args = 1, default_missing_value = "true")]
    pub merge_after: Option<bool>,

    /// MIREOT the ancestors of generated terms from the input into the
    /// results. `<bool>`.
    #[arg(short = 'a', long, num_args = 1, default_missing_value = "true")]
    pub ancestors: Option<bool>,
    /// If true, include ontology annotations from the merge input.
    /// `<bool>`.
    #[arg(short = 'A', long, num_args = 1, default_missing_value = "true")]
    pub include_annotations: Option<bool>,
    /// If true, collapse the import closure when merging. Accepted for
    /// compatibility. `<bool>`.
    #[arg(short = 'c', long, num_args = 1, default_missing_value = "true")]
    pub collapse_import_closure: Option<bool>,

    #[command(flatten)]
    pub common: crate::cmd::CommonArgs,
}

pub fn run(args: Args) -> anyhow::Result<()> {
    step(None, &args)?;
    Ok(())
}

pub fn step(
    piped: Option<crate::model::Model>,
    args: &Args,
) -> anyhow::Result<Option<crate::model::Model>> {
    // --template and --external-template are processed identically.
    let templates: Vec<PathBuf> = args
        .template
        .iter()
        .chain(args.external_template.iter())
        .cloned()
        .collect();
    if templates.is_empty() {
        bail!("template requires at least one --template file");
    }
    let force = args.force.unwrap_or(false);

    // `template` emits ONLY the generated axioms: without
    // `--merge-before`/`--merge-after` the result is the fresh ontology built from
    // the rows. The input is there to resolve labels, not to be carried — a
    // component such as EFO's `components/gwas_import.owl` is the template's own
    // axioms, not the whole of `efo-edit.owl` plus the template.
    //
    // `--ancestors` is approximated by merging the whole input rather than
    // MIREOTing the ancestors of the generated terms; it is a superset, and no
    // repo owlmake builds passes the flag. Warn only when there is nothing
    let merge = args.merge_before.unwrap_or(false) || args.merge_after.unwrap_or(false);
    let needs_input = merge || args.ancestors.unwrap_or(false);
    if needs_input && piped.is_none() && args.input.is_none() {
        status!("template: --merge-before/--merge-after/--ancestors given but no input ontology to merge with");
    }

    let mut model = match piped {
        Some(m) => m,
        None => match args.input.as_deref() {
            Some(p) => io::load(p)?,
            None => Model::from_parts(SetOntology::new(), default_prefixes()),
        },
    };
    args.common.apply(&mut model)?;

    let b = Build::new();
    // Errors collected across all template tables: (table, row, column, message).
    let mut errors: Vec<TemplateError> = Vec::new();

    // Build the label→IRI index from the input ontology's rdfs:label assertions,
    // then augment it with every template's own ID/LABEL rows so cells in any
    // table can reference entities defined in another table by label.
    let mut labels = label_index_from_ontology(&model);

    // Parse and stage all tables first so the label index is complete before any
    // cell is parsed: one pass collects labels, the next builds axioms.
    struct Parsed {
        table: String,
        templates: Vec<String>,
        rows: Vec<(usize, Vec<String>)>,
    }
    let mut parsed_tables: Vec<Parsed> = Vec::new();
    for path in &templates {
        let text = std::fs::read_to_string(path)?;
        let delim = if path.extension().map(|e| e == "csv").unwrap_or(false) {
            ','
        } else {
            '\t'
        };
        // Quoted fields are part of the grammar, not an escape a splitter can
        // ignore: a cell reading `"""Ghost teeth"""` holds `"Ghost teeth"`.
        let rows: Vec<Vec<String>> = crate::table::read(&text, delim);
        if rows.len() < 2 {
            let msg = format!(
                "template {} needs at least a header row and a template-string row",
                path.display()
            );
            if force {
                errors.push(TemplateError::table(path, msg));
                continue;
            }
            bail!("{msg}");
        }
        let header = rows[1].clone();
        let table = path.display().to_string();
        let data: Vec<(usize, Vec<String>)> = rows
            .iter()
            .enumerate()
            .skip(2)
            .map(|(ri, d)| (ri + 1, d.clone()))
            .collect();
        // Index labels declared in this table.
        for (_, d) in &data {
            index_row_label(&model, &header, d, &mut labels);
        }
        parsed_tables.push(Parsed { table, templates: header, rows: data });
    }

    // The generated axioms go into their own ontology, which carries the input's
    // prefixes so a cell's CURIE expands the same way it would have.
    let mut out = Model::from_parts(SetOntology::new(), crate::model::clone_prefixes(&model.prefixes));
    for p in &parsed_tables {
        for (row, data) in &p.rows {
            apply_row(&b, &mut out, &p.templates, data, &p.table, *row, &labels, &mut errors);
        }
    }

    if !errors.is_empty() {
        if let Some(path) = &args.errors {
            write_errors(path, &errors)?;
            status!("template: wrote {} error(s) to {}", errors.len(), path.display());
        }
        for e in errors.iter().take(20) {
            status!("template error [{}:{}] {}: {}", e.table, e.row, e.column, e.message);
        }
        if !force {
            bail!(
                "template: {} error(s); rerun with --force true to continue",
                errors.len()
            );
        }
    }

    // Either merge into the input and return that, or return the generated
    // ontology alone (`--merge-before` and `--merge-after` differ only in whether
    // the un-merged output is the one written to `--output`, which owlmake does
    // not distinguish because it writes once, at the end).
    let mut model = if merge || args.ancestors.unwrap_or(false) {
        for ac in out.ont.iter() {
            model.ont.insert(ac.clone());
        }
        model
    } else {
        out
    };

    // --include-annotations (default false): keep the merged input's ontology
    // annotations only when asked; otherwise strip them (the template itself emits
    // none, so these can only have come from the input).
    if !args.include_annotations.unwrap_or(false) {
        let anns: Vec<_> = model
            .ont
            .iter()
            .filter(|ac| matches!(ac.component, Component::OntologyAnnotation(_)))
            .cloned()
            .collect();
        for ac in anns {
            model.ont.remove(&ac);
        }
    }
    // --collapse-import-closure: drop any owl:imports from the (merged) result.
    if args.collapse_import_closure.unwrap_or(false) {
        let imports: Vec<_> = model
            .ont
            .iter()
            .filter(|ac| matches!(ac.component, Component::Import(_)))
            .cloned()
            .collect();
        for ac in imports {
            model.ont.remove(&ac);
        }
    }

    // Set the output ontology / version IRI, reusing annotate's core.
    if args.ontology_iri.is_some() || args.version_iri.is_some() {
        model = crate::cmd::annotate::annotate_with(
            model,
            &crate::cmd::annotate::AnnotateOptions {
                ontology_iri: args.ontology_iri.clone(),
                version_iri: args.version_iri.clone(),
                ..Default::default()
            },
        )?;
    }

    // `template` builds a NEW ontology from the rows, and a new ontology has a
    // fresh document format — so the prefix block it writes is the bare default
    // set, not the input's. Same rule as `filter` and `query --update`. OBA's
    // `components/synonyms.owl` and `obsoletes.owl` come out of `template`, and
    // carrying the input's prefixes through would change every downstream artefact.
    model.format_prefixes_cleared = true;
    crate::cmd::maybe_save(&mut model, args.output.as_deref(), args.format.as_deref())?;
    Ok(Some(model))
}

/// Generate axioms from a single template table given as text (TSV, or CSV when
/// `csv` is true), inserting them into `model`. The in-memory core behind the
/// `template` command — no files. Template-cell errors are joined into the
/// returned `Err`.
///
/// Layout: row 0 is the column-name/label row, row 1 the template-string row,
/// rows 2.. the data.
pub fn template_from_str(mut model: Model, table: &str, csv: bool) -> anyhow::Result<Model> {
    let b = Build::new();
    let mut labels = label_index_from_ontology(&model);
    let delim = if csv { ',' } else { '\t' };
    // Quoted fields are part of the grammar, not an escape a splitter can ignore:
    // a cell reading `"""Ghost teeth"""` holds `"Ghost teeth"`.
    let rows: Vec<Vec<String>> = crate::table::read(table, delim);
    if rows.len() < 2 {
        bail!("template needs at least a header row and a template-string row");
    }
    let header = rows[1].clone();
    let data: Vec<(usize, Vec<String>)> = rows
        .iter()
        .enumerate()
        .skip(2)
        .map(|(ri, d)| (ri + 1, d.clone()))
        .collect();
    for (_, d) in &data {
        index_row_label(&model, &header, d, &mut labels);
    }
    let mut errors: Vec<TemplateError> = Vec::new();
    for (row, d) in &data {
        apply_row(&b, &mut model, &header, d, "template", *row, &labels, &mut errors);
    }
    if !errors.is_empty() {
        let joined = errors
            .iter()
            .take(20)
            .map(|e| format!("[{}:{}] {}: {}", e.table, e.row, e.column, e.message))
            .collect::<Vec<_>>()
            .join("; ");
        bail!("template: {} error(s): {joined}", errors.len());
    }
    Ok(model)
}

/// A single template processing error — one row of the `--errors` table.
struct TemplateError {
    table: String,
    row: usize,
    column: String,
    message: String,
}

impl TemplateError {
    fn table(path: &std::path::Path, message: String) -> Self {
        TemplateError {
            table: path.display().to_string(),
            row: 0,
            column: String::new(),
            message,
        }
    }
}

fn write_errors(path: &std::path::Path, errors: &[TemplateError]) -> anyhow::Result<()> {
    let csv = path.extension().map(|e| e == "csv").unwrap_or(false);
    let sep = if csv { ',' } else { '\t' };
    let mut out = String::new();
    out.push_str(&["table", "row", "column", "message"].join(&sep.to_string()));
    out.push('\n');
    for e in errors {
        let cells = [e.table.clone(), e.row.to_string(), e.column.clone(), e.message.clone()];
        let line = cells
            .iter()
            .map(|c| {
                if csv && (c.contains(',') || c.contains('"')) {
                    format!("\"{}\"", c.replace('"', "\"\""))
                } else {
                    c.clone()
                }
            })
            .collect::<Vec<_>>()
            .join(&sep.to_string());
        out.push_str(&line);
        out.push('\n');
    }
    std::fs::write(path, out)?;
    Ok(())
}

// === Label index =========================================================

/// Collect rdfs:label → IRI mappings from the ontology's existing assertions.
fn label_index_from_ontology(model: &Model) -> HashMap<String, String> {
    let mut map = HashMap::new();
    for ac in model.ont.iter() {
        if let Component::AnnotationAssertion(aa) = &ac.component {
            if aa.ann.ap.0.as_ref() == RDFS_LABEL {
                if let (AnnotationSubject::IRI(s), AnnotationValue::Literal(lit)) =
                    (&aa.subject, &aa.ann.av)
                {
                    map.insert(literal_text(lit), s.as_ref().to_string());
                }
            }
        }
    }
    map
}

/// Index the (ID, LABEL) pair of one template data row, so later cells can refer
/// to this entity by its label.
fn index_row_label(
    model: &Model,
    templates: &[String],
    data: &[String],
    labels: &mut HashMap<String, String>,
) {
    let mut id: Option<String> = None;
    let mut label: Option<String> = None;
    for (i, tmpl) in templates.iter().enumerate() {
        let cell = match data.get(i) {
            Some(c) if !c.is_empty() => c,
            _ => continue,
        };
        match tmpl.as_str() {
            "ID" => id = Some(expand_t(model, cell)),
            "LABEL" => label = Some(cell.clone()),
            _ => {}
        }
    }
    if let (Some(id), Some(label)) = (id, label) {
        labels.entry(label).or_insert(id);
    }
}

fn literal_text(lit: &Literal<RcStr>) -> String {
    match lit {
        Literal::Simple { literal }
        | Literal::Language { literal, .. }
        | Literal::Datatype { literal, .. } => literal.clone(),
    }
}

// === Subject typing ======================================================

/// The kind of entity a template row's subject is, controlling which
/// declaration is emitted and how the logical-axiom headers behave.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum SubjectType {
    Class,
    ObjectProperty,
    DataProperty,
    AnnotationProperty,
    Individual,
    Datatype,
}

impl SubjectType {
    /// Parse a TYPE / CLASS_TYPE / ... cell value to a subject type.
    fn from_cell(value: &str) -> Option<SubjectType> {
        match value.trim().to_ascii_lowercase().as_str() {
            "class" | "owl:class" => Some(SubjectType::Class),
            "object property" | "owl:objectproperty" | "objectproperty" => {
                Some(SubjectType::ObjectProperty)
            }
            "data property" | "owl:datatypeproperty" | "datatypeproperty" | "dataproperty" => {
                Some(SubjectType::DataProperty)
            }
            "annotation property" | "owl:annotationproperty" | "annotationproperty" => {
                Some(SubjectType::AnnotationProperty)
            }
            "individual" | "named individual" | "owl:namedindividual" | "namedindividual" => {
                Some(SubjectType::Individual)
            }
            "datatype" | "rdfs:datatype" => Some(SubjectType::Datatype),
            _ => None,
        }
    }
}

// === Row processing ======================================================

#[allow(clippy::too_many_arguments)]
fn apply_row(
    b: &Build<RcStr>,
    model: &mut Model,
    templates: &[String],
    data: &[String],
    table: &str,
    row: usize,
    labels: &HashMap<String, String>,
    errors: &mut Vec<TemplateError>,
) {
    // 1. Subject IRI from the ID column.
    let mut id: Option<String> = None;
    for (i, tmpl) in templates.iter().enumerate() {
        if tmpl == "ID" {
            if let Some(cell) = data.get(i) {
                if !cell.is_empty() {
                    id = Some(expand_t(model, cell));
                }
            }
        }
    }
    let id = match id {
        Some(i) => i,
        None => {
            errors.push(TemplateError {
                table: table.to_string(),
                row,
                column: "ID".to_string(),
                message: "row has no value in the ID column".to_string(),
            });
            return;
        }
    };

    // 2. Subject type from any TYPE / *_TYPE column (default: class).
    let mut subject_type = SubjectType::Class;
    for (i, tmpl) in templates.iter().enumerate() {
        let head = tmpl.trim();
        let is_type_header = matches!(
            head,
            "TYPE" | "CLASS_TYPE" | "PROPERTY_TYPE" | "INDIVIDUAL_TYPE"
        );
        if !is_type_header {
            continue;
        }
        if let Some(cell) = data.get(i) {
            if let Some(t) = SubjectType::from_cell(cell) {
                subject_type = t;
            }
        }
    }
    declare_subject(b, model, &id, subject_type);

    // 3. Process columns in order, tracking the axiom generated by each so a
    //    following `>` (axiom-annotation) column can attach to it. The resolver
    //    owns a snapshot of the prefix map (not a borrow of `model`) so the loop
    //    can still mutate `model.ont` while resolving entity references.
    let resolver = make_resolver(robot_context_prefixes(model), labels);
    let mut last_axiom: Option<AnnotatedComponent<RcStr>> = None;
    let mut last_col_index: Option<usize> = None;

    for (i, tmpl) in templates.iter().enumerate() {
        let raw_header = tmpl.trim();
        if raw_header.is_empty() {
            continue;
        }

        // Axiom-annotation header (begins with `>`, not `>>`-only sentinel): it
        // annotates the axiom produced by the most recent non-`>` column.
        if raw_header.starts_with('>') {
            let cell = match data.get(i) {
                Some(c) if !c.trim().is_empty() => c.clone(),
                _ => continue,
            };
            // `>` and `>>` both attach to the last produced axiom (we flatten
            // nested levels to one, since owlmake stores a flat annotation set).
            let inner = raw_header.trim_start_matches('>').trim();
            if let Some(ax) = last_axiom.as_mut() {
                let (inner_t, split) = parse_split(inner);
                let values: Vec<String> = match split {
                    Some(c) => cell.split(c).map(str::to_string).collect(),
                    None => vec![cell],
                };
                for value in values {
                    match build_annotation(b, model, &inner_t, &value, &resolver) {
                        Ok(ann) => {
                            ax.ann.insert(ann);
                        }
                        Err(message) => errors.push(TemplateError {
                            table: table.to_string(),
                            row,
                            column: raw_header.to_string(),
                            message,
                        }),
                    }
                }
            }
            continue;
        }

        // A new non-`>` column: flush the previously-built axiom into the model.
        if let (Some(ax), Some(_)) = (last_axiom.take(), last_col_index.take()) {
            model.ont.insert(ax);
        }

        let cell = match data.get(i) {
            Some(c) if !c.trim().is_empty() => c.clone(),
            _ => continue,
        };
        let (header, split) = parse_split(raw_header);
        let values: Vec<String> = match split {
            Some(c) => cell.split(c).map(str::to_string).collect(),
            None => vec![cell],
        };

        // Headers that emit at most one axiom we want to carry for `>` columns.
        // When SPLIT yields multiple values each is a separate axiom; we insert
        // all but the last immediately and keep the last as `last_axiom`.
        let mut produced: Vec<AnnotatedComponent<RcStr>> = Vec::new();
        for value in &values {
            match apply_template(b, model, &id, subject_type, &header, value, &resolver) {
                Ok(Some(ax)) => produced.push(ax),
                Ok(None) => {}
                Err(message) => errors.push(TemplateError {
                    table: table.to_string(),
                    row,
                    column: header.clone(),
                    message,
                }),
            }
        }
        // Insert all but the last; retain the last for possible `>` annotation.
        if let Some(last) = produced.pop() {
            for ax in produced {
                model.ont.insert(ax);
            }
            last_axiom = Some(last);
            last_col_index = Some(i);
        }
    }
    // Flush any trailing axiom.
    if let Some(ax) = last_axiom.take() {
        model.ont.insert(ax);
    }
}

/// Build the entity resolver closure passed to the Manchester parser: try the
/// label index first, then CURIE/IRI expansion (so cells may mix both). Owns a
/// cloned prefix map so it does not borrow the (mutated) model.
fn make_resolver<'a>(
    prefixes: horned_owl::curie::PrefixMapping,
    labels: &'a HashMap<String, String>,
) -> impl Fn(&str) -> Option<String> + 'a {
    move |tok: &str| {
        let t = tok.trim();
        if t.is_empty() {
            return None;
        }
        if let Some(iri) = labels.get(t) {
            return Some(iri.clone());
        }
        // Full IRI in <...> or bare http(s) — pass through.
        if t.starts_with("http://") || t.starts_with("https://") || t.starts_with("urn:") {
            return Some(t.to_string());
        }
        // CURIE: resolve against the prefix map, falling back to the OBO PURL
        // convention for prefixed ids whose prefix is not declared.
        if t.contains(':') {
            return Some(expand_curie(&prefixes, t));
        }
        None
    }
}

/// Expand a template cell's CURIE against the prefix map template cells resolve
/// through — the model's prefixes with `dc:` rebound, per
/// [`robot_context_prefixes`] — falling back to the model-aware resolution
/// (labels, bare OBO ids) for anything that is not a plain `prefix:local`.
fn expand_t(model: &Model, s: &str) -> String {
    if let Some((prefix, rest)) = s.split_once(':') {
        if !prefix.is_empty() && !rest.starts_with("//") {
            if let Ok(v) = robot_context_prefixes(model).expand_curie_string(s) {
                return v;
            }
        }
    }
    let expanded = select::expand(model, s);
    // A template cell is one of the DOCUMENT's own ids, not a command-line term:
    // it follows the `PREFIX:LOCAL` → `obo/PREFIX_LOCAL` convention whatever any
    // context binds, exactly as [`expand_curie`] just below does. `select::expand`
    // dropped that fallback when the command-line term rule was corrected — right
    // for a `--term`, wrong here, and it left an `EX:partof` ID column declaring
    // `<EX:partof>`.
    if expanded == s && s.contains(':') && !s.starts_with("http") {
        return crate::io::obo::expand_id(s);
    }
    expanded
}

/// The model's prefix map with `dc:` rebound for template-cell expansion.
///
/// In a template cell `dc:` binds to `http://purl.org/dc/TERMS/` — NOT
/// dc/elements/1.1/, which is what a document declares and what the writers'
/// prefix tables hold. OBA's `templates/synonyms.tsv` declares its contributor
/// column `AI dc:contributor`, and the two expansions are different properties,
/// so the wrong one lands on 31 axioms of every downstream artefact.
fn robot_context_prefixes(model: &Model) -> horned_owl::curie::PrefixMapping {
    let mut p = crate::model::clone_prefixes(&model.prefixes);
    let _ = p.add_prefix("dc", "http://purl.org/dc/terms/");
    p
}

/// CURIE/IRI expansion mirroring [`select::expand`] but against a standalone
/// prefix map rather than a whole `Model`.
fn expand_curie(prefixes: &horned_owl::curie::PrefixMapping, s: &str) -> String {
    let s = s.trim();
    let s = s.strip_prefix('<').and_then(|x| x.strip_suffix('>')).unwrap_or(s);
    if s.starts_with("http://") || s.starts_with("https://") || s.starts_with("urn:") {
        return s.to_string();
    }
    if let Ok(expanded) = prefixes.expand_curie_string(s) {
        return expanded;
    }
    if s.contains(':') {
        crate::io::obo::expand_id(s)
    } else {
        s.to_string()
    }
}

/// Declare the subject as the right entity kind.
fn declare_subject(b: &Build<RcStr>, model: &mut Model, id: &str, ty: SubjectType) {
    let c = match ty {
        SubjectType::Class => Component::DeclareClass(DeclareClass(b.class(id))),
        SubjectType::ObjectProperty => {
            Component::DeclareObjectProperty(DeclareObjectProperty(b.object_property(id)))
        }
        SubjectType::DataProperty => {
            Component::DeclareDataProperty(DeclareDataProperty(b.data_property(id)))
        }
        SubjectType::AnnotationProperty => {
            Component::DeclareAnnotationProperty(DeclareAnnotationProperty(b.annotation_property(id)))
        }
        SubjectType::Individual => {
            Component::DeclareNamedIndividual(DeclareNamedIndividual(b.named_individual(id)))
        }
        SubjectType::Datatype => Component::DeclareDatatype(DeclareDatatype(b.datatype(id))),
    };
    model.ont.insert(c);
}

fn parse_split(tmpl: &str) -> (String, Option<char>) {
    if let Some(idx) = tmpl.find("SPLIT=") {
        let before = tmpl[..idx].trim().to_string();
        let c = tmpl[idx + 6..].trim().chars().next();
        (before, c)
    } else {
        (tmpl.to_string(), None)
    }
}

/// Apply one template header to one cell value, returning the generated axiom
/// (as an `AnnotatedComponent` so a following `>` column can annotate it), or
/// `None` for headers that emit directly / are no-ops.
fn apply_template(
    b: &Build<RcStr>,
    model: &mut Model,
    id: &str,
    subject_type: SubjectType,
    tmpl: &str,
    value: &str,
    resolver: &(dyn Fn(&str) -> Option<String> + '_),
) -> Result<Option<AnnotatedComponent<RcStr>>, String> {
    let subject_iri = b.iri(id);
    let tmpl = tmpl.trim();

    // Headers with an argument: "<KEY> <rest>".
    let (key, rest) = match tmpl.split_once(char::is_whitespace) {
        Some((k, r)) => (k, r.trim()),
        None => (tmpl, ""),
    };

    match key {
        "" | "ID" | "TYPE" | "CLASS_TYPE" | "PROPERTY_TYPE" | "INDIVIDUAL_TYPE" => Ok(None),

        "LABEL" => Ok(Some(comp(Component::AnnotationAssertion(AnnotationAssertion {
            subject: AnnotationSubject::IRI(subject_iri),
            ann: lit_ann(b, RDFS_LABEL, value),
        })))),

        // --- Annotations ------------------------------------------------
        // `A <prop>` literal, `AT <prop>^^<dt>` typed, `AL <prop>@<lang>` lang,
        // `AI <prop>` IRI value. Returned (not inserted directly) so a following
        // `>` column can annotate the resulting assertion axiom.
        "A" | "AT" | "AL" | "AI" => {
            let ann = build_annotation(b, model, tmpl, value, resolver)?;
            Ok(Some(comp(Component::AnnotationAssertion(AnnotationAssertion {
                subject: AnnotationSubject::IRI(subject_iri),
                ann,
            }))))
        }

        // --- Class axioms ----------------------------------------------
        "C" | "SC" => {
            let ce = parse_ce(b, rest, value, resolver)?;
            let sub = subject_ce(b, id);
            Ok(Some(comp(Component::SubClassOf(SubClassOf { sub, sup: ce }))))
        }
        "EC" => {
            let ce = parse_ce(b, rest, value, resolver)?;
            Ok(Some(comp(Component::EquivalentClasses(EquivalentClasses(vec![
                subject_ce(b, id),
                ce,
            ])))))
        }
        "DC" => {
            let ce = parse_ce(b, rest, value, resolver)?;
            Ok(Some(comp(Component::DisjointClasses(DisjointClasses(vec![
                subject_ce(b, id),
                ce,
            ])))))
        }

        // --- Object-property axioms ------------------------------------
        "SP" => {
            let sup = resolve_ope(b, rest, value, resolver)?;
            Ok(Some(comp(Component::SubObjectPropertyOf(SubObjectPropertyOf {
                sub: OPE::ObjectProperty(b.object_property(id)).into(),
                sup,
            }))))
        }
        "EP" => {
            let other = resolve_ope(b, rest, value, resolver)?;
            Ok(Some(comp(Component::EquivalentObjectProperties(
                EquivalentObjectProperties(vec![OPE::ObjectProperty(b.object_property(id)), other]),
            ))))
        }
        "DP" => {
            let other = resolve_ope(b, rest, value, resolver)?;
            Ok(Some(comp(Component::DisjointObjectProperties(DisjointObjectProperties(
                vec![OPE::ObjectProperty(b.object_property(id)), other],
            )))))
        }
        "IP" => {
            let other = resolve_ope(b, rest, value, resolver)?;
            Ok(Some(comp(Component::InverseObjectProperties(
                horned_owl::model::InverseObjectProperties(
                    OPE::ObjectProperty(b.object_property(id)),
                    other,
                ),
            ))))
        }
        "DOMAIN" => {
            let ce = parse_ce(b, rest, value, resolver)?;
            Ok(Some(comp(Component::ObjectPropertyDomain(
                horned_owl::model::ObjectPropertyDomain {
                    ope: OPE::ObjectProperty(b.object_property(id)),
                    ce,
                },
            ))))
        }
        "RANGE" => {
            let ce = parse_ce(b, rest, value, resolver)?;
            Ok(Some(comp(Component::ObjectPropertyRange(
                horned_owl::model::ObjectPropertyRange {
                    ope: OPE::ObjectProperty(b.object_property(id)),
                    ce,
                },
            ))))
        }

        // --- Property characteristics ----------------------------------
        "CHARACTERISTIC" => {
            let ope = OPE::ObjectProperty(b.object_property(id));
            let c = characteristic(value, ope)
                .ok_or_else(|| format!("unknown property characteristic '{value}'"))?;
            Ok(Some(comp(c)))
        }

        // --- Individual axioms -----------------------------------------
        // `I`/`TI`: class assertion (the individual is of the cell's type).
        "I" | "TI" => {
            let ce = parse_ce(b, rest, value, resolver)?;
            Ok(Some(comp(Component::ClassAssertion(
                horned_owl::model::ClassAssertion {
                    ce,
                    i: Individual::Named(b.named_individual(id)),
                },
            ))))
        }
        "SI" => {
            let other = resolve_individual(b, value, resolver)?;
            Ok(Some(comp(Component::SameIndividual(
                horned_owl::model::SameIndividual(vec![
                    Individual::Named(b.named_individual(id)),
                    other,
                ]),
            ))))
        }
        "DI" => {
            let other = resolve_individual(b, value, resolver)?;
            Ok(Some(comp(Component::DifferentIndividuals(
                horned_owl::model::DifferentIndividuals(vec![
                    Individual::Named(b.named_individual(id)),
                    other,
                ]),
            ))))
        }

        _ => {
            // Everything not matched above emits no axiom: a plain human-readable
            // column header, which carries no axiom to emit, but equally a template
            // string owlmake has not implemented, which does and silently loses it.
            let _ = subject_type;
            Ok(None)
        }
    }
}

/// Wrap a component as an annotation-less `AnnotatedComponent`.
fn comp(c: Component<RcStr>) -> AnnotatedComponent<RcStr> {
    AnnotatedComponent::from(c)
}

/// The subject of a class axiom as a class expression.
fn subject_ce(b: &Build<RcStr>, id: &str) -> CE<RcStr> {
    CE::Class(b.class(id))
}

/// Parse a class-expression cell. A cell is full Manchester syntax; a header
/// carrying a `%` placeholder (or a bare `%`) is also accepted, with `%` replaced
/// by the cell value before parsing.
fn parse_ce(
    b: &Build<RcStr>,
    header_rest: &str,
    value: &str,
    resolver: &(dyn Fn(&str) -> Option<String> + '_),
) -> Result<CE<RcStr>, String> {
    let expr = manchester_template_expr(header_rest, value);
    manchester_parse::parse_class_expression(b, &expr, &|t| resolver(t))
}

/// Produce the Manchester string to parse from a class-axiom header and cell.
///
/// The usual layout puts the whole expression in the cell, leaving the header as
/// just the axiom keyword (e.g. header `SC`, cell `'part of' some heart`). A
/// header that contains a `%` placeholder (e.g. `SC % some bone`) is honoured too,
/// substituting the cell value for `%`; and a bare `%` header means "use the
/// cell verbatim".
fn manchester_template_expr(header_rest: &str, value: &str) -> String {
    let hr = header_rest.trim();
    if hr.is_empty() || hr == "%" {
        value.to_string()
    } else if hr.contains('%') {
        hr.replace('%', value)
    } else {
        // Header carries a fixed expression and ignores the cell (rare). If a
        // cell value is present, treat the header as a template with the value
        // appended only when it contains no entity — otherwise use the header.
        hr.to_string()
    }
}

/// Resolve a property cell to an ObjectPropertyExpression (allowing `inverse`).
fn resolve_ope(
    b: &Build<RcStr>,
    header_rest: &str,
    value: &str,
    resolver: &(dyn Fn(&str) -> Option<String> + '_),
) -> Result<OPE<RcStr>, String> {
    let expr = manchester_template_expr(header_rest, value);
    let expr = expr.trim();
    let (inverse, name) = match expr.strip_prefix("inverse ") {
        Some(r) => (true, r.trim()),
        None => (false, expr),
    };
    let name = name.trim().trim_matches('\'');
    let iri = resolver(name).ok_or_else(|| format!("could not resolve property '{name}'"))?;
    let op = b.object_property(iri);
    Ok(if inverse {
        OPE::InverseObjectProperty(op)
    } else {
        OPE::ObjectProperty(op)
    })
}

/// Resolve an individual cell to an Individual.
fn resolve_individual(
    b: &Build<RcStr>,
    value: &str,
    resolver: &(dyn Fn(&str) -> Option<String> + '_),
) -> Result<Individual<RcStr>, String> {
    let name = value.trim().trim_matches('\'');
    let iri = resolver(name).ok_or_else(|| format!("could not resolve individual '{name}'"))?;
    Ok(Individual::Named(b.named_individual(iri)))
}

/// Build a property-characteristic axiom from a keyword and a property.
fn characteristic(value: &str, ope: OPE<RcStr>) -> Option<Component<RcStr>> {
    Some(match value.trim().to_ascii_lowercase().as_str() {
        "functional" => Component::FunctionalObjectProperty(
            horned_owl::model::FunctionalObjectProperty(ope),
        ),
        "inverse functional" | "inversefunctional" => {
            Component::InverseFunctionalObjectProperty(
                horned_owl::model::InverseFunctionalObjectProperty(ope),
            )
        }
        "transitive" => {
            Component::TransitiveObjectProperty(horned_owl::model::TransitiveObjectProperty(ope))
        }
        "symmetric" => {
            Component::SymmetricObjectProperty(horned_owl::model::SymmetricObjectProperty(ope))
        }
        "asymmetric" => {
            Component::AsymmetricObjectProperty(horned_owl::model::AsymmetricObjectProperty(ope))
        }
        "reflexive" => {
            Component::ReflexiveObjectProperty(horned_owl::model::ReflexiveObjectProperty(ope))
        }
        "irreflexive" => {
            Component::IrreflexiveObjectProperty(horned_owl::model::IrreflexiveObjectProperty(ope))
        }
        _ => return None,
    })
}

/// Build an annotation from an `A`/`AT`/`AL`/`AI` header and cell value.
///
/// Header forms:
///   `A <prop>`              simple literal
///   `AT <prop>^^<datatype>` typed literal
///   `AL <prop>@<lang>`      language-tagged literal
///   `AI <prop>`             IRI value (the cell is an entity ref)
fn build_annotation(
    b: &Build<RcStr>,
    model: &mut Model,
    header: &str,
    value: &str,
    resolver: &(dyn Fn(&str) -> Option<String> + '_),
) -> Result<Annotation<RcStr>, String> {
    let header = header.trim();
    let (key, rest) = header
        .split_once(char::is_whitespace)
        .map(|(k, r)| (k, r.trim()))
        .ok_or_else(|| format!("annotation header '{header}' is missing a property"))?;
    match key {
        "A" => {
            let prop = expand_t(model, rest);
            declare_annotation_property(b, model, &prop);
            Ok(lit_ann(b, &prop, value))
        }
        "AT" => {
            // `AT prop^^datatype`
            let (prop, dt) = rest
                .split_once("^^")
                .ok_or_else(|| format!("AT header '{header}' must be 'AT prop^^datatype'"))?;
            let prop = expand_t(model, prop.trim());
            let dt_iri = expand_t(model, dt.trim().trim_start_matches('<').trim_end_matches('>'));
            declare_annotation_property(b, model, &prop);
            Ok(Annotation { ann: Default::default(),
                ap: b.annotation_property(prop.as_str()),
                av: AnnotationValue::Literal(Literal::Datatype {
                    literal: value.trim().to_string(),
                    datatype_iri: b.iri(dt_iri.as_str()),
                }),
            })
        }
        "AL" => {
            // `AL prop@lang`
            let (prop, lang) = rest
                .split_once('@')
                .ok_or_else(|| format!("AL header '{header}' must be 'AL prop@lang'"))?;
            let prop = expand_t(model, prop.trim());
            declare_annotation_property(b, model, &prop);
            Ok(Annotation { ann: Default::default(),
                ap: b.annotation_property(prop.as_str()),
                av: AnnotationValue::Literal(Literal::Language {
                    literal: value.trim().to_string(),
                    lang: lang.trim().to_string(),
                }),
            })
        }
        "AI" => {
            let prop = expand_t(model, rest);
            let target = resolver(value.trim())
                .unwrap_or_else(|| select::expand(model, value));
            declare_annotation_property(b, model, &prop);
            Ok(Annotation { ann: Default::default(),
                ap: b.annotation_property(prop.as_str()),
                av: AnnotationValue::IRI(b.iri(target.as_str())),
            })
        }
        other => Err(format!("unsupported annotation header '{other}'")),
    }
}

/// Declare a template-referenced annotation property: every property used in an
/// annotation column gets a `Declaration(AnnotationProperty(...))` — except the
/// OWL/RDF/RDFS/XSD built-ins (`rdfs:label`, `owl:deprecated`, …), which are
/// already known.
fn declare_annotation_property(b: &Build<RcStr>, model: &mut Model, prop: &str) {
    if is_builtin_vocabulary(prop) {
        return;
    }
    model.ont.insert(Component::DeclareAnnotationProperty(
        DeclareAnnotationProperty(b.annotation_property(prop)),
    ));
}

/// True for IRIs in the RDF/RDFS/OWL/XSD namespaces — the built-in vocabulary a
/// template never re-declares.
fn is_builtin_vocabulary(iri: &str) -> bool {
    const BUILTIN_NS: [&str; 4] = [
        "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
        "http://www.w3.org/2000/01/rdf-schema#",
        "http://www.w3.org/2002/07/owl#",
        "http://www.w3.org/2001/XMLSchema#",
    ];
    BUILTIN_NS.iter().any(|ns| iri.starts_with(ns))
}

fn lit_ann(b: &Build<RcStr>, prop: &str, value: &str) -> Annotation<RcStr> {
    Annotation { ann: Default::default(),
        ap: b.annotation_property(prop),
        av: AnnotationValue::Literal(Literal::Simple {
            literal: value.to_string(),
        }),
    }
}
