# AUTO-GENERATED by scripts/generate.py from the owlmake CLI spec.
# Do not edit by hand: re-run the generator after changing the Rust CLI.
"""Typed bindings for the owlmake `sssom` sub-CLI."""

from __future__ import annotations

from typing import Mapping, Optional, Sequence

from . import _runtime as _rt
from ._runtime import Chain, OwlmakeResult, StrOrPath

def convert(input: Optional[StrOrPath] = None, *, output: Optional[StrOrPath] = None, output_format: Optional[StrOrPath] = None, propagate: Optional[bool] = None, condense: Optional[bool] = None, binary: Optional[StrOrPath] = None, cwd: Optional[StrOrPath] = None, env: Optional[Mapping[str, str]] = None, capture: bool = True, raise_on_error: bool = True, timeout: Optional[float] = None) -> OwlmakeResult:
    """Convert a mapping set to another serialization (TSV/CSV/JSON/RDF/OWL).

    Arguments:
    input: [required] Input mapping set.
    output: (--output / -o) Output path (default: stdout).
    output_format: (--output-format / -O) Output format (tsv/csv/json/owl/ttl/...).
    propagate: (--propagate / --no-propagate) (default True) Propagate set-level slots onto each mapping row.
    condense: (--condense / --no-condense) (default True) Condense multi-valued slots in the output.
    """
    return _rt.run_sssom('convert', {
        "input": input,
        "output": output,
        "output_format": output_format,
        "propagate": propagate,
        "condense": condense,
    }, {}, binary=binary, cwd=cwd, env=env, capture=capture, raise_on_error=raise_on_error, timeout=timeout)


def parse(input: Optional[StrOrPath] = None, *, input_format: Optional[StrOrPath] = None, metadata: Optional[StrOrPath] = None, output: Optional[StrOrPath] = None, mapping_predicate_filter: Optional[Sequence[StrOrPath]] = None, prefix_map_mode: Optional[StrOrPath] = None, propagate: Optional[bool] = None, condense: Optional[bool] = None, clean_prefixes: Optional[bool] = None, strict_clean_prefixes: Optional[bool] = None, embedded_mode: Optional[bool] = None, binary: Optional[StrOrPath] = None, cwd: Optional[StrOrPath] = None, env: Optional[Mapping[str, str]] = None, capture: bool = True, raise_on_error: bool = True, timeout: Optional[float] = None) -> OwlmakeResult:
    """Parse a mapping set, apply defaults/cleaning, and re-serialize as SSSOM TSV.

    Arguments:
    input: [required] Input mapping set.
    input_format: (--input-format / -I) Input format override.
    metadata: (--metadata / -m) External metadata YAML.
    output: (--output / -o) Output path (default: stdout).
    mapping_predicate_filter: (--mapping-predicate-filter / -F) Keep only these predicate ids (repeatable).
    prefix_map_mode: (--prefix-map-mode / -C) Prefix-map handling mode.
    propagate: (--propagate / --no-propagate) (default True) Propagate set-level slots onto each mapping row.
    condense: (--condense / --no-condense) (default True) Condense multi-valued slots in the output.
    clean_prefixes: (--clean-prefixes / --no-clean-prefixes) (default True) Drop unused curie_map entries.
    strict_clean_prefixes: (--strict-clean-prefixes / --no-strict-clean-prefixes) (default True) Error on CURIEs whose prefix is undeclared.
    embedded_mode: (--embedded-mode / --non-embedded-mode) (default True) Embed metadata in the TSV (vs sidecar).
    """
    return _rt.run_sssom('parse', {
        "input": input,
        "input_format": input_format,
        "metadata": metadata,
        "output": output,
        "mapping_predicate_filter": mapping_predicate_filter,
        "prefix_map_mode": prefix_map_mode,
        "propagate": propagate,
        "condense": condense,
        "clean_prefixes": clean_prefixes,
        "strict_clean_prefixes": strict_clean_prefixes,
        "embedded_mode": embedded_mode,
    }, {}, binary=binary, cwd=cwd, env=env, capture=capture, raise_on_error=raise_on_error, timeout=timeout)


def validate(input: Optional[StrOrPath] = None, *, validation_types: Optional[Sequence[StrOrPath]] = None, propagate: Optional[bool] = None, binary: Optional[StrOrPath] = None, cwd: Optional[StrOrPath] = None, env: Optional[Mapping[str, str]] = None, capture: bool = True, raise_on_error: bool = True, timeout: Optional[float] = None) -> OwlmakeResult:
    """Validate a mapping set (JsonSchema / PrefixMapCompleteness / StrictCurieFormat).

    Arguments:
    input: [required] Input mapping set.
    validation_types: (--validation-types / -V) Validation types to run (repeatable).
    propagate: (--propagate / --no-propagate) (default True) Propagate set-level slots onto each mapping row.
    """
    return _rt.run_sssom('validate', {
        "input": input,
        "validation_types": validation_types,
        "propagate": propagate,
    }, {}, binary=binary, cwd=cwd, env=env, capture=capture, raise_on_error=raise_on_error, timeout=timeout)


def split(input: Optional[StrOrPath] = None, *, output_directory: Optional[StrOrPath] = None, method: Optional[StrOrPath] = None, binary: Optional[StrOrPath] = None, cwd: Optional[StrOrPath] = None, env: Optional[Mapping[str, str]] = None, capture: bool = True, raise_on_error: bool = True, timeout: Optional[float] = None) -> OwlmakeResult:
    """Split a mapping set into one file per (subject,predicate,object) prefix group.

    Arguments:
    input: [required] Input mapping set.
    output_directory: (--output-directory / -d) Directory for the split files.
    method: (--method) Splitting method.
    """
    return _rt.run_sssom('split', {
        "input": input,
        "output_directory": output_directory,
        "method": method,
    }, {}, binary=binary, cwd=cwd, env=env, capture=capture, raise_on_error=raise_on_error, timeout=timeout)


def dedupe(input: Optional[StrOrPath] = None, *, output: Optional[StrOrPath] = None, binary: Optional[StrOrPath] = None, cwd: Optional[StrOrPath] = None, env: Optional[Mapping[str, str]] = None, capture: bool = True, raise_on_error: bool = True, timeout: Optional[float] = None) -> OwlmakeResult:
    """Remove duplicate mappings, keeping the highest-confidence row per key.

    Arguments:
    input: [required] Input mapping set.
    output: (--output / -o) Output path (default: stdout).
    """
    return _rt.run_sssom('dedupe', {
        "input": input,
        "output": output,
    }, {}, binary=binary, cwd=cwd, env=env, capture=capture, raise_on_error=raise_on_error, timeout=timeout)


def diff(left: Optional[StrOrPath] = None, right: Optional[StrOrPath] = None, *, output: Optional[StrOrPath] = None, binary: Optional[StrOrPath] = None, cwd: Optional[StrOrPath] = None, env: Optional[Mapping[str, str]] = None, capture: bool = True, raise_on_error: bool = True, timeout: Optional[float] = None) -> OwlmakeResult:
    """Diff two mapping sets by (subject,predicate,object).

    Arguments:
    left: [required] First mapping set.
    right: [required] Second mapping set.
    output: (--output / -o) Output path (default: stdout).
    """
    return _rt.run_sssom('diff', {
        "left": left,
        "right": right,
        "output": output,
    }, {}, binary=binary, cwd=cwd, env=env, capture=capture, raise_on_error=raise_on_error, timeout=timeout)


def merge(*inputs: StrOrPath, output: Optional[StrOrPath] = None, propagate: Optional[bool] = None, condense: Optional[bool] = None, reconcile: Optional[bool] = None, binary: Optional[StrOrPath] = None, cwd: Optional[StrOrPath] = None, env: Optional[Mapping[str, str]] = None, capture: bool = True, raise_on_error: bool = True, timeout: Optional[float] = None) -> OwlmakeResult:
    """Merge several mapping sets into one (optionally reconciling redundancy).

    Arguments:
    inputs: [required] Input mapping sets.
    output: (--output / -o) Output path (default: stdout).
    propagate: (--propagate / --no-propagate) (default True) Propagate set-level slots onto each mapping row.
    condense: (--condense / --no-condense) (default True) Condense multi-valued slots in the output.
    reconcile: (--reconcile) (default False) Drop lower-confidence redundant rows.
    """
    return _rt.run_sssom('merge', {
        "inputs": inputs,
        "output": output,
        "propagate": propagate,
        "condense": condense,
        "reconcile": reconcile,
    }, {}, binary=binary, cwd=cwd, env=env, capture=capture, raise_on_error=raise_on_error, timeout=timeout)


def sort(input: Optional[StrOrPath] = None, *, output: Optional[StrOrPath] = None, by_columns: Optional[bool] = None, by_rows: Optional[bool] = None, binary: Optional[StrOrPath] = None, cwd: Optional[StrOrPath] = None, env: Optional[Mapping[str, str]] = None, capture: bool = True, raise_on_error: bool = True, timeout: Optional[float] = None) -> OwlmakeResult:
    """Sort a mapping set by columns and/or rows.

    Arguments:
    input: [required] Input mapping set.
    output: (--output / -o) Output path (default: stdout).
    by_columns: (--by-columns) (default False) Sort columns into canonical order.
    by_rows: (--by-rows) (default False) Sort rows.
    """
    return _rt.run_sssom('sort', {
        "input": input,
        "output": output,
        "by_columns": by_columns,
        "by_rows": by_rows,
    }, {}, binary=binary, cwd=cwd, env=env, capture=capture, raise_on_error=raise_on_error, timeout=timeout)


def filter(input: Optional[StrOrPath] = None, *, output: Optional[StrOrPath] = None, slots: Optional[Mapping[str, StrOrPath]] = None, binary: Optional[StrOrPath] = None, cwd: Optional[StrOrPath] = None, env: Optional[Mapping[str, str]] = None, capture: bool = True, raise_on_error: bool = True, timeout: Optional[float] = None) -> OwlmakeResult:
    """Filter mappings by one or more mapping-slot constraints (glob `*` supported).

    Arguments:
    input: [required] Input mapping set.
    output: (--output / -o) Output path (default: stdout).
    """
    return _rt.run_sssom('filter', {
        "input": input,
        "output": output,
    }, slots or {}, binary=binary, cwd=cwd, env=env, capture=capture, raise_on_error=raise_on_error, timeout=timeout)


def annotate(input: Optional[StrOrPath] = None, *, output: Optional[StrOrPath] = None, replace_multivalued: Optional[bool] = None, slots: Optional[Mapping[str, StrOrPath]] = None, binary: Optional[StrOrPath] = None, cwd: Optional[StrOrPath] = None, env: Optional[Mapping[str, str]] = None, capture: bool = True, raise_on_error: bool = True, timeout: Optional[float] = None) -> OwlmakeResult:
    """Set or append mapping-set metadata slots.

    Arguments:
    input: [required] Input mapping set.
    output: (--output / -o) Output path (default: stdout).
    replace_multivalued: (--replace-multivalued) (default False) Replace rather than append multi-valued slots.
    """
    return _rt.run_sssom('annotate', {
        "input": input,
        "output": output,
        "replace_multivalued": replace_multivalued,
    }, slots or {}, binary=binary, cwd=cwd, env=env, capture=capture, raise_on_error=raise_on_error, timeout=timeout)


def remove(input: Optional[StrOrPath] = None, *, output: Optional[StrOrPath] = None, remove_map: Optional[StrOrPath] = None, binary: Optional[StrOrPath] = None, cwd: Optional[StrOrPath] = None, env: Optional[Mapping[str, str]] = None, capture: bool = True, raise_on_error: bool = True, timeout: Optional[float] = None) -> OwlmakeResult:
    """Remove from a mapping set every mapping present in another set.

    Arguments:
    input: [required] Input mapping set.
    output: (--output / -o) Output path (default: stdout).
    remove_map: (--remove-map) Mapping set whose rows to remove (required).
    """
    return _rt.run_sssom('remove', {
        "input": input,
        "output": output,
        "remove_map": remove_map,
    }, {}, binary=binary, cwd=cwd, env=env, capture=capture, raise_on_error=raise_on_error, timeout=timeout)


def invert(input: Optional[StrOrPath] = None, *, output: Optional[StrOrPath] = None, subject_prefix: Optional[StrOrPath] = None, inverse_map: Optional[StrOrPath] = None, merge_inverted: Optional[bool] = None, update_justification: Optional[bool] = None, binary: Optional[StrOrPath] = None, cwd: Optional[StrOrPath] = None, env: Optional[Mapping[str, str]] = None, capture: bool = True, raise_on_error: bool = True, timeout: Optional[float] = None) -> OwlmakeResult:
    """Invert mapping predicates (and subject/object), optionally merging with the input.

    Arguments:
    input: [required] Input mapping set.
    output: (--output / -o) Output path (default: stdout).
    subject_prefix: (--subject-prefix / -P) Restrict to this subject prefix.
    inverse_map: (--inverse-map) Custom inverse-predicate map.
    merge_inverted: (--merge-inverted / --no-merge-inverted) (default True) Append inverted rows to the originals.
    update_justification: (--update-justification / --no-update-justification) (default True) Set mapping_justification to MappingInversion.
    """
    return _rt.run_sssom('invert', {
        "input": input,
        "output": output,
        "subject_prefix": subject_prefix,
        "inverse_map": inverse_map,
        "merge_inverted": merge_inverted,
        "update_justification": update_justification,
    }, {}, binary=binary, cwd=cwd, env=env, capture=capture, raise_on_error=raise_on_error, timeout=timeout)


def reconcile_prefixes(input: Optional[StrOrPath] = None, *, output: Optional[StrOrPath] = None, reconcile_prefix_file: Optional[StrOrPath] = None, binary: Optional[StrOrPath] = None, cwd: Optional[StrOrPath] = None, env: Optional[Mapping[str, str]] = None, capture: bool = True, raise_on_error: bool = True, timeout: Optional[float] = None) -> OwlmakeResult:
    """Rewrite CURIEs/curie_map using a prefix reconciliation YAML.

    Arguments:
    input: [required] Input mapping set.
    output: (--output / -o) Output path (default: stdout).
    reconcile_prefix_file: (--reconcile-prefix-file / -p) Reconciliation YAML (required).
    """
    return _rt.run_sssom('reconcile-prefixes', {
        "input": input,
        "output": output,
        "reconcile_prefix_file": reconcile_prefix_file,
    }, {}, binary=binary, cwd=cwd, env=env, capture=capture, raise_on_error=raise_on_error, timeout=timeout)


def crosstab(input: Optional[StrOrPath] = None, *, output: Optional[StrOrPath] = None, fields: Optional[Sequence[StrOrPath]] = None, transpose: Optional[bool] = None, binary: Optional[StrOrPath] = None, cwd: Optional[StrOrPath] = None, env: Optional[Mapping[str, str]] = None, capture: bool = True, raise_on_error: bool = True, timeout: Optional[float] = None) -> OwlmakeResult:
    """Tabulate a contingency table of two mapping slots.

    Arguments:
    input: [required] Input mapping set.
    output: (--output / -o) Output path (default: stdout).
    fields: (--fields / -f) Row and column slot names (two values).
    transpose: (--transpose) (default False) Transpose rows and columns.
    """
    return _rt.run_sssom('crosstab', {
        "input": input,
        "output": output,
        "fields": fields,
        "transpose": transpose,
    }, {}, binary=binary, cwd=cwd, env=env, capture=capture, raise_on_error=raise_on_error, timeout=timeout)


def correlations(input: Optional[StrOrPath] = None, *, output: Optional[StrOrPath] = None, fields: Optional[Sequence[StrOrPath]] = None, transpose: Optional[bool] = None, binary: Optional[StrOrPath] = None, cwd: Optional[StrOrPath] = None, env: Optional[Mapping[str, str]] = None, capture: bool = True, raise_on_error: bool = True, timeout: Optional[float] = None) -> OwlmakeResult:
    """Alias of `crosstab` (same tabulation engine).

    Arguments:
    input: [required] Input mapping set.
    output: (--output / -o) Output path (default: stdout).
    fields: (--fields / -f) Row and column slot names (two values).
    transpose: (--transpose) (default False) Transpose rows and columns.
    """
    return _rt.run_sssom('correlations', {
        "input": input,
        "output": output,
        "fields": fields,
        "transpose": transpose,
    }, {}, binary=binary, cwd=cwd, env=env, capture=capture, raise_on_error=raise_on_error, timeout=timeout)


def partition(*inputs: StrOrPath, output_directory: Optional[StrOrPath] = None, binary: Optional[StrOrPath] = None, cwd: Optional[StrOrPath] = None, env: Optional[Mapping[str, str]] = None, capture: bool = True, raise_on_error: bool = True, timeout: Optional[float] = None) -> OwlmakeResult:
    """Partition merged mappings into connected-component cliques.

    Arguments:
    inputs: [required] Input mapping sets.
    output_directory: (--output-directory / -d) Directory for the partition files.
    """
    return _rt.run_sssom('partition', {
        "inputs": inputs,
        "output_directory": output_directory,
    }, {}, binary=binary, cwd=cwd, env=env, capture=capture, raise_on_error=raise_on_error, timeout=timeout)


def cliquesummary(input: Optional[StrOrPath] = None, *, output: Optional[StrOrPath] = None, metadata: Optional[StrOrPath] = None, statsfile: Optional[StrOrPath] = None, binary: Optional[StrOrPath] = None, cwd: Optional[StrOrPath] = None, env: Optional[Mapping[str, str]] = None, capture: bool = True, raise_on_error: bool = True, timeout: Optional[float] = None) -> OwlmakeResult:
    """Summarize mapping cliques (id, size, members).

    Arguments:
    input: [required] Input mapping set.
    output: (--output / -o) Output path (default: stdout).
    metadata: (--metadata / -m) External metadata.
    statsfile: (--statsfile / -s) Stats output file.
    """
    return _rt.run_sssom('cliquesummary', {
        "input": input,
        "output": output,
        "metadata": metadata,
        "statsfile": statsfile,
    }, {}, binary=binary, cwd=cwd, env=env, capture=capture, raise_on_error=raise_on_error, timeout=timeout)


def rewire(input: Optional[StrOrPath] = None, *, output: Optional[StrOrPath] = None, mapping_file: Optional[StrOrPath] = None, input_format: Optional[StrOrPath] = None, output_format: Optional[StrOrPath] = None, precedence: Optional[Sequence[StrOrPath]] = None, binary: Optional[StrOrPath] = None, cwd: Optional[StrOrPath] = None, env: Optional[Mapping[str, str]] = None, capture: bool = True, raise_on_error: bool = True, timeout: Optional[float] = None) -> OwlmakeResult:
    """Rewrite an ontology, collapsing entities linked by equivalence mappings.

    Arguments:
    input: [required] Input ontology.
    output: (--output / -o) Output path (default: stdout).
    mapping_file: (--mapping-file / -m) SSSOM mapping set (required).
    input_format: (--input-format / -I) Ontology input format.
    output_format: (--output-format / -O) Ontology output format.
    precedence: (--precedence) Prefix precedence for ambiguous targets (repeatable).
    """
    return _rt.run_sssom('rewire', {
        "input": input,
        "output": output,
        "mapping_file": mapping_file,
        "input_format": input_format,
        "output_format": output_format,
        "precedence": precedence,
    }, {}, binary=binary, cwd=cwd, env=env, capture=capture, raise_on_error=raise_on_error, timeout=timeout)


def xref_extract(input: Optional[StrOrPath] = None, *, output: Optional[StrOrPath] = None, mapping_file: Optional[StrOrPath] = None, map_prefix_to_predicate: Optional[Sequence[StrOrPath]] = None, all_xrefs: Optional[bool] = None, drop_duplicates: Optional[bool] = None, binary: Optional[StrOrPath] = None, cwd: Optional[StrOrPath] = None, env: Optional[Mapping[str, str]] = None, capture: bool = True, raise_on_error: bool = True, timeout: Optional[float] = None) -> OwlmakeResult:
    """Extract oboInOwl:hasDbXref annotations into a SSSOM mapping set.

    Arguments:
    input: Input ontology (accepted positionally or as --input).
    output: (--output / -o) Output path.
    mapping_file: (--mapping-file) Output mapping file.
    map_prefix_to_predicate: (--map-prefix-to-predicate) 'PREFIX PREDICATE' assignment (repeatable).
    all_xrefs: (--all-xrefs) (default False) Extract xrefs of every prefix.
    drop_duplicates: (--drop-duplicates) (default False) Drop duplicate (s,p,o) rows.
    """
    return _rt.run_sssom('xref-extract', {
        "input": input,
        "output": output,
        "mapping_file": mapping_file,
        "map_prefix_to_predicate": map_prefix_to_predicate,
        "all_xrefs": all_xrefs,
        "drop_duplicates": drop_duplicates,
    }, {}, binary=binary, cwd=cwd, env=env, capture=capture, raise_on_error=raise_on_error, timeout=timeout)


def ptable(*inputs: StrOrPath, binary: Optional[StrOrPath] = None, cwd: Optional[StrOrPath] = None, env: Optional[Mapping[str, str]] = None, capture: bool = True, raise_on_error: bool = True, timeout: Optional[float] = None) -> OwlmakeResult:
    """Recognized but not yet implemented in owlmake.

    NOTE: the arguments are parsed and the call reports the gap; nothing is computed.

    Arguments:
    inputs: Inputs.
    """
    return _rt.run_sssom('ptable', {
        "inputs": inputs,
    }, {}, binary=binary, cwd=cwd, env=env, capture=capture, raise_on_error=raise_on_error, timeout=timeout)


def dosql(*inputs: StrOrPath, binary: Optional[StrOrPath] = None, cwd: Optional[StrOrPath] = None, env: Optional[Mapping[str, str]] = None, capture: bool = True, raise_on_error: bool = True, timeout: Optional[float] = None) -> OwlmakeResult:
    """Recognized but not yet implemented in owlmake.

    NOTE: the arguments are parsed and the call reports the gap; nothing is computed.

    Arguments:
    inputs: Inputs.
    """
    return _rt.run_sssom('dosql', {
        "inputs": inputs,
    }, {}, binary=binary, cwd=cwd, env=env, capture=capture, raise_on_error=raise_on_error, timeout=timeout)


def sparql(*inputs: StrOrPath, binary: Optional[StrOrPath] = None, cwd: Optional[StrOrPath] = None, env: Optional[Mapping[str, str]] = None, capture: bool = True, raise_on_error: bool = True, timeout: Optional[float] = None) -> OwlmakeResult:
    """Recognized but not yet implemented in owlmake.

    NOTE: the arguments are parsed and the call reports the gap; nothing is computed.

    Arguments:
    inputs: Inputs.
    """
    return _rt.run_sssom('sparql', {
        "inputs": inputs,
    }, {}, binary=binary, cwd=cwd, env=env, capture=capture, raise_on_error=raise_on_error, timeout=timeout)


def serve_rdf(*inputs: StrOrPath, binary: Optional[StrOrPath] = None, cwd: Optional[StrOrPath] = None, env: Optional[Mapping[str, str]] = None, capture: bool = True, raise_on_error: bool = True, timeout: Optional[float] = None) -> OwlmakeResult:
    """Recognized but not yet implemented in owlmake.

    NOTE: the arguments are parsed and the call reports the gap; nothing is computed.

    Arguments:
    inputs: Inputs.
    """
    return _rt.run_sssom('serve-rdf', {
        "inputs": inputs,
    }, {}, binary=binary, cwd=cwd, env=env, capture=capture, raise_on_error=raise_on_error, timeout=timeout)


__all__ = [
    'annotate',
    'cliquesummary',
    'convert',
    'correlations',
    'crosstab',
    'dedupe',
    'diff',
    'dosql',
    'filter',
    'invert',
    'merge',
    'parse',
    'partition',
    'ptable',
    'reconcile_prefixes',
    'remove',
    'rewire',
    'serve_rdf',
    'sort',
    'sparql',
    'split',
    'validate',
    'xref_extract',
]
