// Writes tests/fixtures/owlapi-literals/cases.tsv: lexical forms, the datatype
// or language tag each is made with, and the literal OWL API's data factory
// makes of them — the cases owlmake's literals (src/model.rs) are held to.
//
// Run through scripts/gen_owlapi_literals.sh, with ROBOT's jar on the class path.

import java.math.BigDecimal;
import java.math.MathContext;
import java.util.*;
import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.*;

public class GenOwlapiLiterals {
    static final String XSD = "http://www.w3.org/2001/XMLSchema#";
    static final String RDF = "http://www.w3.org/1999/02/22-rdf-syntax-ns#";
    static final OWLDataFactory DF = OWLManager.getOWLDataFactory();

    public static void main(String[] args) {
        System.out.println("# Generated by scripts/gen_owlapi_literals.sh from OWL API " + args[0] + " on Java "
            + System.getProperty("java.version") + ". Do not edit.");
        System.out.println("# lexical\tmade with\tlexical\tlanguage\tdatatype");
        String[] booleans = {"true", "false", "1", "0", " true ", "\t1\n", " 0 ", "TRUE", "True", "yes", "", " ", "tru"};
        String[] numbers = {"1", "1.0", "1.50", "-0.0", " -0.0 ", "0.0", "-0", "0", "+0", "00", "007", "-007", "+007",
            "+5", "-5", "5", " 5", "5 ", "1e3", "1E3", "1e-3", "1e+3", "1e", "e5", ".5", "5.", ".", "+", "-", "1.e5",
            "1.0e7", "1.0E7", "9999999", "10000000", "0.001", "0.0009999", "1.16", "0.1", "0.2", "0.3", "100",
            "1234567.0", "12345678.0", "-1.25e-10", "16777216", "16777217", "123456789", "2147483647", "2147483648",
            "-2147483648", "-2147483649", "99999999999", "123456789012345678", "9007199254740993",
            "NaN", "-NaN", "+NaN", "Infinity", "-Infinity", "+Infinity", "INF", "-INF", "inf", "nan", "NAN",
            "1f", "1F", "1d", "1D", "1.5f ", " 2.5 ", " 2.5", "0x1p3", "0x1.8p1", "0X1P-2f", "0x.8p1", "0x10",
            "abc", "1_0", "1,5", "1.5.5", "--1", "٣", "０", "1.4e-45", "1e-45", "7e-45", "2.8e-45",
            "1.17549435E-38", "1.1754942E-38", "3.4028235e38", "3.4028236e38", "1e39", "-1e39", "4.9e-324",
            "5e-324", "1e-400", "2.4703282292062327e-324", "2.4703282292062328e-324", "2.2250738585072014E-308",
            "1.7976931348623157e308", "1.8e308", "1e23", "2e23", "8.41e21", "1.0E-5"};
        String[] numeric = {"float", "double", "integer", "decimal", "int", "long", "nonNegativeInteger", "byte"};
        for (String lex : booleans) row(lex, XSD + "boolean");
        for (String type : numeric) for (String lex : numbers) row(lex, XSD + type);
        String[] plain = {"x@en", "x@EN-gb", "x", "x@", "@en", "a@b@c", "x@ en ", "", "@", "x@EN", "x@İ"};
        for (String lex : plain) {
            row(lex, RDF + "PlainLiteral");
            row(lex, RDF + "langString");
            row(lex, XSD + "string");
        }
        for (String lang : new String[] {"en", "EN", " en ", "EN-GB", "en-GB", "İ", "Σ", "x-Private"})
            langRow("x", lang);
        for (String lex : new String[] {"x", " x ", "1", "true"}) {
            row(lex, XSD + "anyURI");
            row(lex, XSD + "dateTime");
        }
        // Values whose shortest printing Java and its own parse decide: random
        // finite floats and doubles, written with 25 significant digits.
        Random random = new Random(20261006L);
        for (int i = 0; i < 400; i++) {
            float f = Float.intBitsToFloat(random.nextInt());
            if (Float.isFinite(f)) row(new BigDecimal(f).round(new MathContext(25)).toString(), XSD + "float");
            double d = Double.longBitsToDouble(random.nextLong());
            if (Double.isFinite(d)) row(new BigDecimal(d).round(new MathContext(25)).toString(), XSD + "double");
        }
        for (int i = 0; i < 100; i++) {
            float f = Float.intBitsToFloat(random.nextInt(0x00800000) | (random.nextBoolean() ? 0x80000000 : 0));
            row(new BigDecimal(f).round(new MathContext(25)).toString(), XSD + "float");
            double d = Double.longBitsToDouble((random.nextLong() & 0x000fffffffffffffL));
            row(new BigDecimal(d).round(new MathContext(25)).toString(), XSD + "double");
        }
        for (int i = 0; i < 200; i++) {
            String lex = random.nextInt(10) + "." + (random.nextInt(1000000)) + "e" + (random.nextInt(90) - 45);
            row(lex, XSD + "float");
            row(lex, XSD + "double");
        }
    }

    static void row(String lex, String datatype) {
        print(lex, datatype, DF.getOWLLiteral(lex, DF.getOWLDatatype(IRI.create(datatype))));
    }

    static void langRow(String lex, String lang) {
        print(lex, "@" + lang, DF.getOWLLiteral(lex, lang));
    }

    static void print(String lex, String with, OWLLiteral l) {
        System.out.println(escape(lex) + "\t" + escape(with) + "\t" + escape(l.getLiteral()) + "\t" + escape(l.getLang())
            + "\t" + l.getDatatype().getIRI());
    }

    // A backslash, a tab, a line break and every character outside printable
    // ASCII, as a backslash, `u` and four hex digits.
    static String escape(String s) {
        StringBuilder out = new StringBuilder();
        for (char c : s.toCharArray()) {
            if (c == '\\' || c < 0x20 || c > 0x7e) out.append(String.format("\\u%04x", (int) c));
            else out.append(c);
        }
        return out.toString();
    }
}
