// Writes what owlmake's reading of `java.util.regex` (src/dosdp/java.rs) is
// built and checked against, from the running JDK:
//
//   names      the Unicode block and script names `\p{In\u2026}`, `\p{block=\u2026}` and
//              `\p{script=\u2026}` take, as src/dosdp/java/names.rs;
//   unicode    what `Character` says of each code point: its general category,
//              script and case, the predicates `\p{\u2026}` names, and its type in
//              grapheme segmentation, as src/dosdp/java/unicode.rs;
//   charnames  the character names `\N{\u2026}` takes, deflated, as the file named;
//   cases      tests/fixtures/java-regex/cases.tsv: patterns, inputs and what
//              `Pattern` makes of them.
//
// Run through scripts/gen_java_regex.sh, which writes them all.

import java.io.FileOutputStream;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.function.IntPredicate;
import java.util.function.IntUnaryOperator;
import java.util.regex.*;
import java.util.zip.Deflater;
import java.util.zip.DeflaterOutputStream;

public class GenJavaRegex {
    public static void main(String[] args) throws Exception {
        String mode = args.length > 0 ? args[0] : "";
        if (args.length == 1 && mode.equals("names")) names();
        else if (args.length == 1 && mode.equals("unicode")) unicode();
        else if (args.length == 2 && mode.equals("charnames")) charNames(args[1]);
        else if (args.length == 1 && mode.equals("cases")) cases();
        else throw new IllegalArgumentException("usage: names | unicode | charnames FILE | cases");
    }

    static String generated() {
        return "// Generated by scripts/gen_java_regex.sh from Java " + System.getProperty("java.version")
            + ". Do not edit.\n\n";
    }

    // \u2500\u2500 tables \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500

    @SuppressWarnings("unchecked")
    static void names() throws Exception {
        Field mapField = Character.UnicodeBlock.class.getDeclaredField("map");
        mapField.setAccessible(true);
        Map<String, Character.UnicodeBlock> map = (Map<String, Character.UnicodeBlock>) mapField.get(null);
        Map<Character.UnicodeBlock, TreeSet<String>> names = new HashMap<>();
        for (Map.Entry<String, Character.UnicodeBlock> e : map.entrySet())
            names.computeIfAbsent(e.getValue(), k -> new TreeSet<>()).add(e.getKey());
        // Each block's code points, in code point order.
        LinkedHashMap<Character.UnicodeBlock, int[]> ranges = new LinkedHashMap<>();
        Character.UnicodeBlock prev = null;
        int start = 0;
        for (int cp = 0; cp <= Character.MAX_CODE_POINT + 1; cp++) {
            Character.UnicodeBlock b = cp <= Character.MAX_CODE_POINT ? Character.UnicodeBlock.of(cp) : null;
            if (b != prev) {
                if (prev != null) {
                    if (ranges.containsKey(prev)) throw new IllegalStateException(prev + " is not one range");
                    ranges.put(prev, new int[] {start, cp - 1});
                }
                prev = b;
                start = cp;
            }
        }
        Field aliasField = Character.UnicodeScript.class.getDeclaredField("aliases");
        aliasField.setAccessible(true);
        Map<String, Character.UnicodeScript> aliases = (Map<String, Character.UnicodeScript>) aliasField.get(null);

        StringBuilder out = new StringBuilder(generated());
        out.append("/// A Unicode block: the name it prints as, every name it goes by in\n");
        out.append("/// `\\p{InName}` and `\\p{block=Name}`, in upper case, and the code points it\n");
        out.append("/// holds (none for a block that holds none).\n");
        out.append("pub(super) type Block = (&'static str, &'static [&'static str], Option<(u32, u32)>);\n\n");
        out.append("/// Every Unicode block.\n");
        out.append("pub(super) const BLOCKS: &[Block] = &[\n");
        List<Character.UnicodeBlock> order = new ArrayList<>(ranges.keySet());
        for (Character.UnicodeBlock b : names.keySet()) if (!ranges.containsKey(b)) order.add(b);
        for (Character.UnicodeBlock b : order) {
            out.append("    (\"").append(b).append("\", &[");
            boolean first = true;
            for (String n : names.get(b)) {
                out.append(first ? "" : ", ").append('"').append(n).append('"');
                first = false;
            }
            int[] r = ranges.get(b);
            if (r == null) out.append("], None),\n");
            else out.append(String.format("], Some((0x%04X, 0x%04X))),\n", r[0], r[1]));
        }
        out.append("];\n\n");
        out.append("/// Each script `\\p{IsName}` and `\\p{script=Name}` name, in the order\n");
        out.append("/// `unicode::SCRIPTS_OF` numbers them: its name, and the other names it goes\n");
        out.append("/// by, in upper case.\n");
        out.append("pub(super) const SCRIPTS: &[(&str, &[&str])] = &[\n");
        for (Character.UnicodeScript s : Character.UnicodeScript.values()) {
            out.append("    (\"").append(s.name()).append("\", &[");
            boolean first = true;
            for (String a : new TreeSet<>(aliasesOf(aliases, s))) {
                out.append(first ? "" : ", ").append('"').append(a).append('"');
                first = false;
            }
            out.append("]),\n");
        }
        out.append("];\n");
        System.out.print(out);
    }

    /// What `Character` says of every code point, as runs of code points and
    /// what they share.
    static void unicode() throws Exception {
        StringBuilder out = new StringBuilder(generated());
        out.append("//! What `Character` says of each code point, as runs of code points: the\n");
        out.append("//! first, the last and, where it varies, what they share.\n\n");

        out.append("/// `Character.getType` of every code point it does not call UNASSIGNED.\n");
        runs(out, "CATEGORIES", Character::getType, Character.UNASSIGNED);

        out.append("/// `Character.UnicodeScript.of` every code point, by the script's place in\n");
        out.append("/// `names::SCRIPTS`.\n");
        runs(out, "SCRIPTS_OF", cp -> Character.UnicodeScript.of(cp).ordinal(), -1);

        Class<?> grapheme = Class.forName("jdk.internal.util.regex.Grapheme");
        Method type = grapheme.getDeclaredMethod("getType", int.class);
        type.setAccessible(true);
        out.append("/// The type `\\X` and `\\b{g}` give every code point they do not call OTHER\n");
        out.append("/// (`grapheme`'s constants).\n");
        runs(out, "GRAPHEME_TYPES", cp -> {
            try {
                return (Integer) type.invoke(null, cp);
            } catch (ReflectiveOperationException e) {
                throw new IllegalStateException(e);
            }
        }, 0);

        out.append("/// `Character.toUpperCase` and `toLowerCase` of every code point that either\n");
        out.append("/// changes: the code point, its uppercase and its lowercase.\n");
        out.append("pub(super) const CASES: &[(u32, u32, u32)] = &[");
        int n = 0;
        for (int cp = 0; cp <= Character.MAX_CODE_POINT; cp++) {
            int upper = Character.toUpperCase(cp), lower = Character.toLowerCase(cp);
            if (upper == cp && lower == cp) continue;
            out.append(n++ % 4 == 0 ? "\n    " : " ");
            out.append(String.format("(0x%04X, 0x%04X, 0x%04X),", cp, upper, lower));
        }
        out.append("\n];\n\n");

        Object[][] predicates = {
            {"ALPHABETIC", "isAlphabetic"}, {"IDEOGRAPHIC", "isIdeographic"}, {"LOWER_CASE", "isLowerCase"},
            {"UPPER_CASE", "isUpperCase"}, {"MIRRORED", "isMirrored"}, {"WHITESPACE", "isWhitespace"},
            {"EMOJI", "isEmoji"}, {"EMOJI_PRESENTATION", "isEmojiPresentation"},
            {"EMOJI_MODIFIER", "isEmojiModifier"}, {"EMOJI_MODIFIER_BASE", "isEmojiModifierBase"},
            {"EMOJI_COMPONENT", "isEmojiComponent"}, {"EXTENDED_PICTOGRAPHIC", "isExtendedPictographic"},
            {"JAVA_IDENTIFIER_START", "isJavaIdentifierStart"}, {"JAVA_IDENTIFIER_PART", "isJavaIdentifierPart"},
            {"UNICODE_IDENTIFIER_START", "isUnicodeIdentifierStart"},
            {"UNICODE_IDENTIFIER_PART", "isUnicodeIdentifierPart"},
            {"IDENTIFIER_IGNORABLE", "isIdentifierIgnorable"},
        };
        for (Object[] p : predicates) {
            Method m = Character.class.getMethod((String) p[1], int.class);
            out.append("/// The code points `Character.").append(p[1]).append("` holds for.\n");
            ranges(out, (String) p[0], cp -> {
                try {
                    return (Boolean) m.invoke(null, cp);
                } catch (ReflectiveOperationException e) {
                    throw new IllegalStateException(e);
                }
            });
        }
        System.out.print(out);
    }

    /// `name`, the runs of code points `f` gives one value, but `omit`.
    static void runs(StringBuilder out, String name, IntUnaryOperator f, int omit) {
        out.append("pub(super) const ").append(name).append(": &[(u32, u32, u8)] = &[");
        int n = 0, start = 0, value = f.applyAsInt(0);
        for (int cp = 1; cp <= Character.MAX_CODE_POINT + 1; cp++) {
            int v = cp <= Character.MAX_CODE_POINT ? f.applyAsInt(cp) : Integer.MIN_VALUE;
            if (v == value) continue;
            if (value != omit) {
                if (value < 0 || value > 255) throw new IllegalStateException(name + ": " + value);
                out.append(n++ % 5 == 0 ? "\n    " : " ");
                out.append(String.format("(0x%04X, 0x%04X, %d),", start, cp - 1, value));
            }
            start = cp;
            value = v;
        }
        out.append("\n];\n\n");
    }

    /// `name`, the runs of code points `p` holds for.
    static void ranges(StringBuilder out, String name, IntPredicate p) {
        out.append("pub(super) const ").append(name).append(": &[(u32, u32)] = &[");
        int n = 0;
        for (int cp = 0; cp <= Character.MAX_CODE_POINT; cp++) {
            if (!p.test(cp)) continue;
            int start = cp;
            while (cp < Character.MAX_CODE_POINT && p.test(cp + 1)) cp++;
            out.append(n++ % 6 == 0 ? "\n    " : " ");
            out.append(String.format("(0x%04X, 0x%04X),", start, cp));
        }
        out.append("\n];\n\n");
    }

    /// Every character name `Character.codePointOf` finds without working it
    /// out from a block's name, a line `HEX;NAME` each in code point order,
    /// deflated into `path`.
    static void charNames(String path) throws Exception {
        Class<?> names = Class.forName("java.lang.CharacterName");
        Method instance = names.getDeclaredMethod("getInstance");
        instance.setAccessible(true);
        Method name = names.getDeclaredMethod("getName", int.class);
        name.setAccessible(true);
        Object table = instance.invoke(null);
        StringBuilder text = new StringBuilder();
        for (int cp = 0; cp <= Character.MAX_CODE_POINT; cp++) {
            String n = (String) name.invoke(table, cp);
            if (n != null) text.append(String.format("%X;%s\n", cp, n));
        }
        Deflater deflater = new Deflater(Deflater.BEST_COMPRESSION);
        try (DeflaterOutputStream out = new DeflaterOutputStream(new FileOutputStream(path), deflater)) {
            out.write(text.toString().getBytes(StandardCharsets.US_ASCII));
        }
        deflater.end();
    }

    static List<String> aliasesOf(Map<String, Character.UnicodeScript> aliases, Character.UnicodeScript s) {
        List<String> out = new ArrayList<>();
        for (Map.Entry<String, Character.UnicodeScript> e : aliases.entrySet())
            if (e.getValue() == s) out.add(e.getKey());
        return out;
    }

    // \u2500\u2500 cases \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500

    /// What a case line holds, after its kind: `P` a pattern and whether
    /// `find` matches each probe, a bit per probe in order, four to a hex
    /// digit, most significant first, or `E` where the pattern is refused; `D`
    /// the same over each probe written twice; `C` a pattern and the code
    /// points but surrogates it matches on their own, as how many and an FNV-1a
    /// hash of their runs written `FIRST-LAST,` in hex, or `E`; `M` a pattern,
    /// an input and the first match's group spans in UTF-16 units (`-` for a
    /// group that took no part), or `N`, `E`, or `X` where matching throws; `F`
    /// a pattern, an input and every match's span, or `N`, `E` or `X`; `R` a
    /// pattern, an input, a replacement and `replaceFirst`'s result, or `E`.
    static final StringBuilder OUT = new StringBuilder();

    /// The probes: characters of every kind the cases tell apart, the last
    /// few ones whose properties or case changed after Unicode 15.0, which
    /// Java 21 follows.
    static final String[] PROBES = {
        "a", "A", "z", "Z", "k", "K", "s", "S", "i", "I", "0", "9", "_", "-", "$", " ", "\t", "\n",
        "\u000B", "\r", "\u0007", "\u001B", "\u001C", "\u007F", "\u0085", "\u009F", "\u00A0", "\u00A2",
        "\u00AA", "\u00AD", "\u00B2", "\u00B5", "\u00C5", "\u00DF", "\u00E5", "\u00E9", "\u00C9", "\u00F7",
        "\u00FF", "\u0130", "\u0131", "\u0178", "\u017F", "\u01C4", "\u01C5", "\u01C6", "\u02B0", "\u0300",
        "\u0345", "\u0370", "\u0378", "\u0391", "\u0399", "\u039C", "\u03A3", "\u03B1", "\u03B9", "\u03BC",
        "\u03C2", "\u03C3", "\u0410", "\u05D0", "\u0663", "\u0903", "\u0F3A", "\u16EE", "\u1E9E", "\u1F80",
        "\u1F88", "\u1FB3", "\u1FBC", "\u1FBE", "\u200B", "\u200C", "\u2007", "\u2028", "\u2029", "\u202F",
        "\u2060", "\u2126", "\u212A", "\u212B", "\u2160", "\u2E2F", "\u3000", "\u3007", "\u4E2D", "\uE000",
        "\uFDD0", "\uFF10", "\uFF21", "\uFFFD", "\uFFFF", "\uD835\uDC00", "\uD83D\uDE00", "\uD83C\uDFFB",
        "\uD801\uDC00", "\uD801\uDC28", "\uDB40\uDC01", "\uDB80\uDC00", "\uDBFF\uDFFF",
        "\u0264", "\uA7CB", "\u1C89", "\u0897", "\u2FFC", "\u30FB", "\uD805\uDF1E", "\uD87A\uDFF0",
        "\uD83E\uDEE9",
    };

    static String esc(String s) {
        StringBuilder b = new StringBuilder();
        for (char c : s.toCharArray()) {
            if (c < 0x20 || c > 0x7e || c == '\\') b.append(String.format("\\u%04x", (int) c));
            else b.append(c);
        }
        return b.toString();
    }

    static void probe(String kind, String pattern, boolean twice) {
        Pattern p;
        try {
            p = Pattern.compile(pattern);
        } catch (PatternSyntaxException e) {
            OUT.append(kind).append('\t').append(esc(pattern)).append("\tE\n");
            return;
        }
        StringBuilder bits = new StringBuilder();
        for (int i = 0; i < PROBES.length; i += 4) {
            int nibble = 0;
            for (int j = i; j < i + 4; j++) {
                boolean found = j < PROBES.length && p.matcher(twice ? PROBES[j] + PROBES[j] : PROBES[j]).find();
                nibble = nibble << 1 | (found ? 1 : 0);
            }
            bits.append(Character.forDigit(nibble, 16));
        }
        OUT.append(kind).append('\t').append(esc(pattern)).append('\t').append(bits).append('\n');
    }

    static void p(String pattern) { probe("P", pattern, false); }
    static void d(String pattern) { probe("D", pattern, true); }

    static void m(String pattern, String input) {
        OUT.append("M\t").append(esc(pattern)).append('\t').append(esc(input)).append('\t');
        Pattern p;
        try {
            p = Pattern.compile(pattern);
        } catch (PatternSyntaxException e) {
            OUT.append("E\n");
            return;
        }
        Matcher m = p.matcher(input);
        try {
            if (!m.find()) {
                OUT.append("N\n");
                return;
            }
        } catch (RuntimeException e) {
            OUT.append("X\n");
            return;
        }
        for (int g = 0; g <= m.groupCount(); g++) {
            OUT.append(g == 0 ? "" : ";");
            OUT.append(m.start(g) < 0 ? "-" : m.start(g) + "," + m.end(g));
        }
        OUT.append('\n');
    }

    static void f(String pattern, String input) {
        OUT.append("F\t").append(esc(pattern)).append('\t').append(esc(input)).append('\t');
        Pattern p;
        try {
            p = Pattern.compile(pattern);
        } catch (PatternSyntaxException e) {
            OUT.append("E\n");
            return;
        }
        Matcher m = p.matcher(input);
        StringBuilder spans = new StringBuilder();
        try {
            while (m.find()) spans.append(spans.length() == 0 ? "" : ";").append(m.start()).append(',').append(m.end());
        } catch (RuntimeException e) {
            OUT.append("X\n");
            return;
        }
        OUT.append(spans.length() == 0 ? "N" : spans).append('\n');
    }

    /// Every code point but the surrogates, as text.
    static final String[] ALL = new String[Character.MAX_CODE_POINT + 1];
    static {
        for (int cp = 0; cp <= Character.MAX_CODE_POINT; cp++)
            if (!Character.isSurrogate((char) cp) || cp > 0xFFFF) ALL[cp] = new String(Character.toChars(cp));
    }

    static void c(String pattern) {
        OUT.append("C\t").append(esc(pattern)).append('\t');
        Pattern p;
        try {
            p = Pattern.compile(pattern);
        } catch (PatternSyntaxException e) {
            OUT.append("E\n");
            return;
        }
        Matcher m = p.matcher("");
        StringBuilder runs = new StringBuilder();
        int count = 0, start = -1;
        for (int cp = 0; cp <= Character.MAX_CODE_POINT + 1; cp++) {
            boolean in = cp <= Character.MAX_CODE_POINT && ALL[cp] != null && m.reset(ALL[cp]).matches();
            if (in) {
                count++;
                if (start < 0) start = cp;
            } else if (start >= 0) {
                runs.append(String.format("%X-%X,", start, cp - 1));
                start = -1;
            }
        }
        long hash = 0xcbf29ce484222325L;
        for (byte b : runs.toString().getBytes(StandardCharsets.US_ASCII)) {
            hash ^= b & 0xff;
            hash *= 0x100000001b3L;
        }
        OUT.append(count).append('\t').append(String.format("%016x", hash)).append('\n');
    }

    static void r(String pattern, String input, String replacement) {
        OUT.append("R\t").append(esc(pattern)).append('\t').append(esc(input)).append('\t')
           .append(esc(replacement)).append('\t');
        try {
            OUT.append(esc(input.replaceFirst(pattern, replacement))).append('\n');
        } catch (RuntimeException e) {
            OUT.append("E\n");
        }
    }

    static void cases() {
        OUT.append("# Generated by scripts/gen_java_regex.sh from Java ")
           .append(System.getProperty("java.version")).append(". Do not edit.\n");
        OUT.append("# probes");
        for (String probe : PROBES) OUT.append('\t').append(esc(probe));
        OUT.append('\n');

        // Character properties, as each prefix and flag reads them.
        String[] names = {
            "L", "Lu", "Ll", "Lt", "Lm", "Lo", "M", "Mn", "Mc", "Me", "N", "Nd", "Nl", "No", "P", "Pc", "Pd",
            "Ps", "Pe", "Pi", "Pf", "Po", "S", "Sm", "Sc", "Sk", "So", "Z", "Zs", "Zl", "Zp", "C", "Cc", "Cf",
            "Co", "Cs", "Cn", "LC", "LD", "L1", "all", "ASCII", "Alnum", "Alpha", "Blank", "Cntrl", "Digit",
            "Graph", "Lower", "Print", "Punct", "Space", "Upper", "XDigit", "javaLowerCase", "javaUpperCase",
            "javaWhitespace", "javaMirrored", "javaAlphabetic", "javaIdeographic", "javaTitleCase", "javaDigit",
            "javaDefined", "javaLetter", "javaLetterOrDigit", "javaJavaIdentifierStart",
            "javaJavaIdentifierPart", "javaUnicodeIdentifierStart", "javaUnicodeIdentifierPart",
            "javaIdentifierIgnorable", "javaSpaceChar", "javaISOControl", "IsL", "IsLu", "IsLatin", "IsGreek",
            "IsAlphabetic", "IsLetter", "IsLowercase", "IsUppercase", "IsTitlecase", "IsPunctuation",
            "IsControl", "IsWhite_Space", "IsWhiteSpace", "IsDigit", "IsHex_Digit", "IsHexDigit",
            "IsJoin_Control", "IsJoinControl", "IsNoncharacter_Code_Point", "IsNoncharacterCodePoint",
            "IsAssigned", "IsIdeographic", "IsEmoji", "IsEmoji_Presentation", "IsEmoji_Modifier",
            "IsEmoji_Modifier_Base", "IsEmoji_Component", "IsExtended_Pictographic", "IsWord", "IsAlnum",
            "IsAlpha", "IsLower", "IsUpper", "IsSpace", "IsPunct", "IsXDigit", "IsCntrl", "IsBlank",
            "IsGraph", "IsPrint", "IsjavaLowerCase", "isLatin", "ISLATIN", "IsLATIN", "Islatin", "Isgreek",
            "IsCommon", "IsInherited", "IsUnknown", "IsHan", "IsCyrillic", "IsArabic", "IsZyyy", "IsZinh",
            "IsZzzz", "IsGrek", "IsHani", "IsASCII", "IsAll", "IsLL", "Isll", "Is_Lu", "IsCased", "IsDash",
            "IsMath", "IsRadical", "IsLu ", "Is Lu", "Greek", "Latin", "Alphabetic", "Lowercase", "Uppercase",
            "White_Space", "Letter", "Punctuation", "Ideographic", "lu", "LU", "l", "alpha", "ALPHA", "lower",
            "LOWER", "punct", "javalowercase", "script=Greek", "sc=Greek", "sc=Grek", "script=GREEK",
            "sc=latin", "script=Latn", "Script=Greek", "SC=Greek", "sc=Common", "sc=Zyyy", "sc=Inherited",
            "sc=Unknown", "sc=Zzzz", "sc=Old_Italic", "sc=OldItalic", "sc=Old Italic", "sc=Han", "sc=Hani",
            "sc=Hira", "sc=Nko", "sc=Signwriting", "sc=Hrkt", "sc=Qaai", "sc=", "gc=Lu", "general_category=Lu",
            "gc=L", "gc=LC", "GC=Lu", "gc=lu", "General_Category=Lu", "gc=Upper", "gc=Lower", "gc=all",
            "gc=javaLowerCase", "block=Greek", "blk=Greek", "blk=GreekandCoptic", "block=Greek and Coptic",
            "blk=GREEK_AND_COPTIC", "blk=greek", "Block=Greek", "BLK=Greek", "InGreek", "InGreekandCoptic",
            "InGreek and Coptic", "InGREEK_AND_COPTIC", "Ingreek", "INGreek", "inGreek", "InBasicLatin",
            "InBasic_Latin", "InBasic Latin", "InLatin-1 Supplement", "InLatin1Supplement",
            "InLatin-1Supplement", "InLATIN_1_SUPPLEMENT", "InCombiningDiacriticalMarks", "InGreekExtended",
            "InLetterlikeSymbols", "InCJKUnifiedIdeographs", "InArabic", "InCombiningMarksforSymbols",
            "InCombining Diacritical Marks for Symbols", "InCyrillicSupplementary", "InCyrillicSupplement",
            "InCyrillic Supplement", "InEmoticons", "InHighSurrogates", "InLow_Surrogates",
            "InSurrogates_Area", "InSpecials", "InPrivateUseArea", "InPrivate Use Area",
            "InSupplementary_Private_Use_Area_A", "InSupplementaryPrivateUseArea-B", "InTags",
            "InMathematicalAlphanumericSymbols", "InDeseret", "InHalfwidth_and_Fullwidth_Forms",
            "InGeneralPunctuation", "InNoSuchBlock", "In", "Is", "Is L", "L&", "",
        };
        for (String n : names) {
            p("\\p{" + n + "}");
            p("\\P{" + n + "}");
            p("(?i)\\p{" + n + "}");
            p("(?U)\\p{" + n + "}");
            p("[x\\p{" + n + "}]");
            p("[^x\\P{" + n + "}]");
            p("(?iu)[\\p{" + n + "}]");
        }
        for (String n : new String[] {"L", "N", "M", "P", "S", "Z", "C", "l", "u", "X", "{", "}"}) {
            p("\\p" + n);
            p("\\P" + n);
            p("[\\p" + n + "]");
        }
        p("\\p");
        p("\\p{L");
        p("[\\p{L]");

        // Literals, classes and ranges under each case flag.
        String[] chars = {
            "a", "A", "k", "K", "s", "S", "i", "I", "\u00B5", "\u00C5", "\u00DF", "\u00E5", "\u00E9",
            "\u00FF", "\u0130", "\u0131", "\u0178", "\u017F", "\u01C4", "\u01C5", "\u01C6", "\u0345", "\u0391",
            "\u0399", "\u039C", "\u03A3", "\u03B1", "\u03B9", "\u03BC", "\u03C2", "\u03C3", "\u1E9E", "\u1F80",
            "\u1F88", "\u1FB3", "\u1FBC", "\u1FBE", "\u2126", "\u212A", "\u212B", "\u2160", "\uD801\uDC00",
            "\uD801\uDC28", "5", "_", "$",
        };
        for (String c : chars) {
            String q = c.equals("$") ? "\\$" : c;
            for (String flags : new String[] {"", "(?i)", "(?iu)", "(?u)", "(?U)", "(?i)(?-i)"}) {
                p(flags + q);
                d(flags + q + q);
                p(flags + "[" + q + "]");
                p(flags + "[^" + q + "]");
                p(flags + String.format("\\x{%X}", c.codePointAt(0)));
                d(flags + String.format("\\x{%X}\\x{%X}", c.codePointAt(0), c.codePointAt(0)));
                p(flags + String.format("[\\x{%X}]", c.codePointAt(0)));
            }
        }
        String[] ranges = {
            "a-z", "A-Z", "Z-a", "a-k", "k-s", "\\x41-\\x5A", "\\x41-Z", "A-\\x5A", "\\u00C0-\\u00FF", "\\u00DF-\\u00FF",
            "\\u00B5-\\u00B5", "\\u0370-\\u03FF", "\\u0390-\\u03A9", "\\u1F80-\\u1F8F", "\\u1FB0-\\u1FBF",
            "\\u2100-\\u214F", "\\u0100-\\u017F", "\\u0130-\\u0131", "\\u01C4-\\u01C6", "\\x{10400}-\\x{1044F}",
            "\\uD800-\\uDFFF", "\\uD7FF-\\uE000", "\\x00-\\x{10FFFF}", "0-9", "!-/", "z-a", "a-\\w", "a-\\p{L}",
        };
        for (String r : ranges) {
            for (String flags : new String[] {"", "(?i)", "(?iu)"}) {
                p(flags + "[" + r + "]");
                p(flags + "[^" + r + "]");
            }
        }

        // Class syntax.
        String[] classes = {
            "[a-]", "[-a]", "[a-[b]]", "[a-[\\d]]", "[\\w-]", "[\\w-a]", "[a&&b]", "[a-z&&[^aeiou]]",
            "[a-z&&k-s&&s]", "[\\p{L}&&\\p{Lu}]", "[^\\p{L}&&\\p{Lu}]", "[a[b]]", "[^a[b]]", "[[a]&&[b]]",
            "[a&&]", "[&&a]", "[a&b]", "[a&&&b]", "[]a]", "[^]a]", "[\\]]", "[\\[]", "[\\Qa-z\\E]",
            "[\\Q]\\E]", "[x\\Q\\E]", "[\\t-\\r]", "[\\0101-\\0132]", "[\\cA-\\cZ]", "[\\u0041-\\u005A]",
            "[\\x{41}-\\x{5A}]", "[\\1]", "[\\k]", "[\\b]", "[\\h]", "[\\v]", "[\\H]", "[\\V]", "[\\R]",
            "[\\s\\S]", "[\\d\\w]", "[\\D]", "[\\W]", "[a-z-0]", "[$-a]", "(?x)[a - z]", "(?x)[ a ]",
            "(?x)[a#]\n]", "[a", "[", "[]", "[^]", "[\\]", "[a-z\\]", "[\\uD83D\\uDE00]", "[\\uD800]",
            "[\\x{D800}]", "[\\x{110000}]", "[\\N{LATIN SMALL LETTER A}]",
        };
        for (String c : classes) {
            for (String flags : new String[] {"", "(?i)", "(?iu)", "(?U)"}) p(flags + c);
        }

        // Escapes, quotation and comments.
        String[] escapes = {
            "\\t", "\\n", "\\r", "\\f", "\\a", "\\e", "\\0101", "\\0", "\\08", "\\0377", "\\0400", "\\x41",
            "\\x4", "\\x{41}", "\\x{}", "\\x{110000}", "\\u0041", "\\u004", "\\uD83D\\uDE00", "\\uD83D",
            "\\uDE00", "\\uD83D\\u0041", "\\cA", "\\c", "\\c?", "\\w", "\\W", "\\d", "\\D", "\\s", "\\S",
            "\\h", "\\H", "\\v", "\\V", "\\R", "\\X", "\\N{LATIN SMALL LETTER A}", "\\b", "\\B", "\\A",
            "\\G", "\\Z", "\\z", "\\E", "\\Q", "\\Qa\\E", "\\Qa-z\\E", "\\Q\\E", "\\Q\\", "\\Q\\\\E",
            "\\Qa\\Eb", "\\Q1\\E", "\\x\\Q1\\E", "\\Q.*\\E", "a\\Q\\E*", "\\Qab\\E*", "\\-", "\\.", "\\\u00E9",
            "\\ ", "\\y", "\\i", "\\j", "\\l", "\\m", "\\o", "\\q", "\\g", "\\K", "\\L", "\\U", "\\T",
            "\\1", "\\k<a>",
        };
        for (String e : escapes) {
            for (String flags : new String[] {"", "(?i)", "(?iu)", "(?U)"}) p(flags + e);
        }
        String[] comments = {
            "(?x)a b", "(?x)a b*", "(?x)ab *", "(?x)a#x\nb", "(?x)a#x\u2028b", "(?x)a#x\u0085b", "(?x)a\u00A0",
            "(?x)a\u2028", "(?x)a\\ b", "(?x)[ ]", "(?x)\\p{ L }", "(?x)a{ 2 }", "(?x)( a )", "(?x)a#",
            "(?x)(?-x)a b", "(?x:a b)c d", "(?xd)a#x\u2028b", "(?x)a\u000Bb", "(?x)a\u000Cb",
        };
        for (String c : comments) p(c);

        // Matches, with groups.
        String[][] matches = {
            {"^(\\w+)\\s(\\d+)$", "abc 123"}, {"^(\\w+)\\s(\\d+)$", "\u00E9 1"}, {"a$", "a\n"},
            {"a$", "a\r\n"}, {"a$", "a\u0085"}, {"a$", "a\u2028"}, {"a$", "a\n\n"}, {"(?m)a$", "a\nb"},
            {"(?m)^b", "a\nb"}, {"(?m)^b", "a\r\nb"}, {"(?m)^b", "a\rb"}, {"(?m)^", "a\n"},
            {"(?m)$", "a\r\n"}, {"(?d)a$", "a\r\n"}, {"(?d)(?m)^b", "a\rb"}, {"a.b", "a\rb"},
            {"a.b", "a\u2028b"}, {"(?s)a.b", "a\nb"}, {"(?d)a.b", "a\rb"}, {"a\\Z", "a\r\n"},
            {"a\\z", "a\n"}, {"\\Aa", "ba"}, {"\\Ga", "ba"}, {"\\b\u00E9", "\u00E9"}, {"(?U)\\b\u00E9", "\u00E9"},
            {"a*+a", "aaa"}, {"(?>a*)a", "aaa"}, {"(?<=x)(a)\\1", "xaa"}, {"(?<!x)a", "xa a"},
            {"(a)|(b)", "b"}, {"(a)?b", "b"}, {"(?<n>a)\\k<n>", "aa"}, {"(a)\\2", "aa"}, {"(a)\\11", "aa1"},
            {"(a)(b)(c)(d)(e)(f)(g)(h)(i)(j)\\10", "abcdefghijj"}, {"(?i)(a)\\1", "aA"},
            {"(?i)(\u00E9)\\1", "\u00E9\u00C9"}, {"(?iu)(\u00E9)\\1", "\u00E9\u00C9"}, {"(?i)\u00E9", "\u00C9"},
            {"(?iu)\u00E9", "\u00C9"}, {"(?i)[a-c]", "B"}, {"a{2}", "aaa"}, {"a{2,}", "aaa"}, {"a{,2}", "aaa"},
            {"a{2,1}", "aaa"}, {"a{", "a{"}, {"a{x", "a{x"}, {"{", "{"}, {"}", "}"}, {"]", "]"}, {"x*?", "xx"},
            {"(?:ab)+", "abab"}, {"\\d+", "\u0663\u0661"}, {"(?U)\\d+", "\u0663\u0661"}, {"\\w", "\u00E9"},
            {"(?U)\\w", "\u00E9"}, {"\\s", "\u00A0"}, {"(?U)\\s", "\u00A0"}, {"\\h", "\u00A0"},
            {"\\v", "\u2028"}, {"\\R", "\r\n"}, {"[a-z]+", "\uD83D\uDE00abc"}, {".", "\uD83D\uDE00"},
            {"\\uD83D\\uDE00", "x\uD83D\uDE00"}, {"\\p{L}+", "a\u00E9\u4E2D1"}, {"\\Qa.b\\E", "axb a.b"},
            {"(?i)\\x41", "a"}, {"(?i)\u00DFa", "\u1E9Ea"}, {"(?iu)\u00DF", "\u1E9E"},
            {"(?iu)\u00DFa", "\u1E9EA"}, {"(?iu)[\u00DF]", "\u1E9E"}, {"(?iu)k", "\u212A"},
            {"(?iu)[k]", "\u212A"}, {"(?iu)[a-z]", "\u212A"}, {"(?i)[a-z]", "\u212A"},
            {"(?iu)\u03C3+", "\u03A3\u03C2\u03C3"}, {"(?iu)[\u03C3]+", "\u03A3\u03C2\u03C3"},
            {"(?iu)(k)\\1", "k\u212A"}, {"(?iu)ss", "\u017F\u017F"}, {"(?iu)\u00DF+", "\u1E9E\u00DF"},
            {"(?iu)a\u00DF+", "a\u1E9E"}, {"(?iu)\u00DFa+", "\u1E9Eaa"}, {"(?x)(?iu)\u00DF a", "\u1E9Ea"},
            {"(?iu)\u00DF\\x{DF}", "\u1E9E\u1E9E"}, {"(?iu)\u00DF\\Q\\E\u00DF", "\u1E9E\u1E9E"},
            {"(?iu)[\u00DF-\u00DF]", "\u1E9E"}, {"(?iu)[\u00DE-\u00DF]", "\u1E9E"}, {"", ""},
            {"", "abc"}, {"a|", "b"}, {"|a", "a"}, {"()", "a"}, {"(?=a)", "a"}, {"(?!)", "a"},
            {"(", "a"}, {")", "a"}, {"(?", "a"}, {"(?<", "a"}, {"(?<1a>a)", "a"}, {"(?<a>a)(?<a>b)", "ab"},
            {"(?q)a", "a"}, {"(?i-i)a", "A"}, {"(?i:a)a", "AA"}, {"(?i:a)a", "Aa"}, {"((?i)a)a", "AA"},
            {"((?i)a)a", "Aa"}, {"a**", "aa"}, {"a*?+", "aa"}, {"a?+a", "a"}, {"*a", "a"}, {"a{1}{2}", "aa"},
        };
        for (String[] t : matches) m(t[0], t[1]);

        // Replacements.
        String[][] replacements = {
            {"(\\w+) (\\w+)", "ab cd", "$2 $1"}, {"(a)", "a", "$12"}, {"(a)", "a", "$2"}, {"(a)", "a", "\\$1"},
            {"(a)", "a", "\\\\"}, {"(a)", "a", "x\\"}, {"(a)", "a", "$"}, {"(a)", "a", "${x}"},
            {"(?<x>a)", "a", "${x}${x}"}, {"(?<x>a)", "a", "${1}"}, {"(a)|(b)", "b", "[$1][$2]"},
            {"x", "abc", "y"}, {"", "abc", "-"}, {"b*", "abc", "-"}, {"(a)(b)(c)(d)(e)(f)(g)(h)(i)(j)(k)", "abcdefghijk", "$11$10$1"},
        };
        for (String[] t : replacements) r(t[0], t[1], t[2]);

        // What each property, shorthand and case-insensitive range matches,
        // over every code point.
        for (String n : names) {
            c("\\p{" + n + "}");
            c("(?i)\\p{" + n + "}");
            c("(?U)\\p{" + n + "}");
        }
        for (String e : new String[] {"w", "W", "d", "D", "s", "S", "h", "H", "v", "V"}) {
            for (String flags : new String[] {"", "(?U)", "(?i)"}) {
                c(flags + "\\" + e);
                c(flags + "[\\" + e + "]");
            }
        }
        for (String dot : new String[] {".", "(?s).", "(?d).", "(?U)."}) c(dot);
        for (Character.UnicodeBlock b : blocksInOrder()) {
            int[] r = blockRange(b);
            c(String.format("(?iu)[\\x{%X}-\\x{%X}]", r[0], r[1]));
        }

        // Character names.
        String[][] named = {
            {"\\N{LATIN SMALL LETTER A}", "a"}, {"\\N{latin small letter a}", "a"},
            {"\\N{ LATIN SMALL LETTER A }", "a"}, {"\\N{\tLATIN SMALL LETTER A\u000B}", "a"},
            {"\\N{LATIN  SMALL LETTER A}", "a"}, {"\\N{LATIN_SMALL_LETTER_A}", "a"},
            {"\\N{LATIN SMALL LETTER SHARP S}", "\u00DF"}, {"\\N{lat\u0131n small letter a}", "a"},
            {"\\N{LATIN \u017FMALL LETTER A}", "a"}, {"\\N{LATIN SMALL LETTER \u00DF}", "a"},
            {"\\N{CJK UNIFIED IDEOGRAPHS 4E00}", "\u4E00"}, {"\\N{cjk unified ideographs 4e00}", "\u4E00"},
            {"\\N{CJK UNIFIED IDEOGRAPH-4E00}", "\u4E00"}, {"\\N{CJK UNIFIED IDEOGRAPHS 04E00}", "\u4E00"},
            {"\\N{CJK UNIFIED IDEOGRAPHS +4E00}", "\u4E00"}, {"\\N{CJK UNIFIED IDEOGRAPHS \uFF14E00}", "\u4E00"},
            {"\\N{CJK_UNIFIED_IDEOGRAPHS 4E00}", "\u4E00"}, {"\\N{HANGUL SYLLABLES AC00}", "\uAC00"},
            {"\\N{HANGUL SYLLABLE GA}", "\uAC00"}, {"\\N{TANGUT 17000}", "\uD81C\uDC00"},
            {"\\N{BASIC LATIN 41}", "A"}, {"\\N{GREEK AND COPTIC 378}", "\u0378"},
            {"\\N{PRIVATE USE AREA E000}", "\uE000"}, {"\\N{HIGH SURROGATES D800}", "a"},
            {"\\N{SUPPLEMENTARY PRIVATE USE AREA-A F0000}", "\uDB80\uDC00"}, {"\\N{NULL}", "\u0000"},
            {"\\N{LINE FEED (LF)}", "\n"}, {"\\N{LINE FEED}", "\n"}, {"\\N{LF}", "\n"}, {"\\N{SPACE}", " "},
            {"\\N{NO-BREAK SPACE}", "\u00A0"}, {"\\N{GRINNING FACE}", "\uD83D\uDE00"},
            {"\\N{BYTE ORDER MARK}", "\uFEFF"}, {"\\N{ZERO WIDTH NO-BREAK SPACE}", "\uFEFF"},
            {"\\N{}", "a"}, {"\\N{", "a"}, {"\\N", "a"}, {"\\Nx", "a"}, {"\\N{LATIN SMALL LETTER A", "a"},
            {"\\N{X}", "a"}, {"\\N{ }", "a"}, {"[\\N{LATIN SMALL LETTER A}-\\N{LATIN SMALL LETTER C}]", "b"},
            {"(?i)\\N{LATIN SMALL LETTER A}", "A"}, {"\\N{LATIN SMALL LETTER A}+", "aaa"},
            {"(?x)\\N {LATIN SMALL LETTER A}", "a"}, {"(?x)\\N{LATIN SMALL LETTER A}", "a"},
            {"(?x)\\N{LATIN SMALL #}\n LETTER A}", "a"}, {"\\N{LATIN SMALL LETTER A}\\N{LATIN SMALL LETTER B}", "ab"},
            {"\\Q\\N{X}\\E", "\\N{X}"}, {"[\\N{LATIN SMALL LETTER A}\\N{DIGIT ONE}]+", "a1"},
        };
        for (String[] t : named) m(t[0], t[1]);

        // Back-references, in and out of case.
        String[][] backrefs = {
            {"(?iu)(\u212A)\\1", "\u212Ak"}, {"(?iu)(s)\\1", "s\u017F"}, {"(?iu)(\u00DF)\\1", "\u00DF\u1E9E"},
            {"(?iu)(\u03C3)\\1\\1", "\u03C3\u03A3\u03C2"}, {"(?iu)(\u01C5)\\1", "\u01C5\u01C6"},
            {"(?i)(K)\\1", "K\u212A"}, {"(?i)(ab)\\1", "abAB"}, {"(?i)(a)(?-i)\\1", "aA"},
            {"(?iu)(kk)\\1", "kkK"}, {"(?i)(?<n>a)\\k<n>", "aA"}, {"(?iu)(\u0130)\\1", "\u0130i"},
            {"(?iu)(\u0131)\\1", "\u0131I"}, {"(?iu)(i)\\1", "i\u0130"}, {"(?iu)(\u0264)\\1", "\u0264\uA7CB"},
            {"(?iu)(\uD801\uDC00)\\1", "\uD801\uDC00\uD801\uDC28"},
            {"(?iu)(\uD801\uDC00)\\1", "\uD801\uDC00\uD801\uDC28x"},
            {"(?iu)(\uD801\uDC00)\\1", "\uD801\uDC00\uD801\uDC28\uD801\uDC28"},
            {"(?iu)(\uD801\uDC00)\\1.", "\uD801\uDC00\uD801\uDC28\uD801\uDC28x"},
            {"(?i)(\uD83D\uDE00)\\1", "\uD83D\uDE00\uD83D\uDE00"},
            {"(?i)(\uD83D\uDE00)\\1", "\uD83D\uDE00\uD83D\uDE00\uD83D\uDE00"},
            {"(?i)(a\uD83D\uDE00)\\1", "a\uD83D\uDE00A\uD83D\uDE00b"}, {"(\uD83D\uDE00)\\1", "\uD83D\uDE00\uD83D\uDE00"},
            {"(?i)(.)\\1", "\uD83D\uDE00\uD83D\uDE00"}, {"(?iu)(\u00E9+)\\1", "\u00E9\u00E9\u00C9\u00C9"},
            {"(?i)(a)\\1*b", "aAaAb"}, {"(?iu)(\u1F80)\\1", "\u1F80\u1F88"}, {"(?iu)(\u1FB3)\\1", "\u1FB3\u1FBC"},
        };
        for (String[] t : backrefs) m(t[0], t[1]);

        // Look-behinds, bounded and not.
        String[][] behind = {
            {"(?<=a*)b", "aab"}, {"(?<=a+)b", "aab"}, {"(?<=a{1,3})b", "aab"}, {"(?<=a{2,})b", "aab"},
            {"(?<=a?)b", "aab"}, {"(?<=a|bc)d", "bcd"}, {"(?<=(a)\\1)b", "aab"}, {"(?<=\\X)b", "ab"},
            {"(?<=\\b{g})b", "ab"}, {"(?<!a*)b", "b"}, {"(?<=\\R)b", "\r\nb"}, {"(?<=a.*)b", "ab"},
            {"(?<=(?:ab)+)c", "abc"}, {"(?<=a*?)b", "ab"}, {"(?<=a*+)b", "ab"}, {"(?<=x(?=y))", "xy"},
            {"(?<=\\Qab\\E)c", "abc"}, {"(?<=\\N{LATIN SMALL LETTER A})b", "ab"}, {"(?<=\\p{L})b", "ab"},
            {"(?<=[\uD801\uDC00])b", "\uD801\uDC00b"}, {"(?<=a{0,1000})b", "ab"}, {"(?<=(?<=a)b)c", "abc"},
            {"(?<=a(?<!b*))c", "ac"}, {"(?<=(?i)(a)\\1)b", "aAb"}, {"(?<=a{2}+)b", "aab"},
        };
        for (String[] t : behind) m(t[0], t[1]);

        // How long Java takes a look-behind to be: refused without a most it
        // can count, never matching when its least passes its most, and
        // searched from its least to its most, the shortest first.
        String[][] lengths = {
            {"(?<=(?:a)*)b", "aab"}, {"(?<=x(?:a)*)b", "xab"}, {"(?<=(?:a|b)*)c", "abc"},
            {"(?<=(?:a|b){2})c", "abc"}, {"(?<=(?:ab){2})c", "ababc"}, {"(?<=[ab]{2})c", "abc"},
            {"(?<=(a|b))c", "bc"}, {"(?<=(a)?)b", "ab"}, {"(?<=(?:ab)?)c", "abc"}, {"(?<=(?:ab)?+)c", "abc"},
            {"(?<=a.*.*b)c", "abc"}, {"(?<=a?b?.*)c", "c"}, {"(?<=a?b?.*)c", "xc"}, {"(?<=a?b?.*)c", "xxc"},
            {"(?<=\\X|ab)c", "abc"}, {"(?<=\\X|ab)c", "e\u0301\u0301c"}, {"(?<=\\p{So})b", "\uD83D\uDE00b"},
            {"(?<=\uD83D\uDE00)b", "\uD83D\uDE00b"}, {"(?<=a(?<=a))b", "ab"}, {"(?<=a{1,3}+)b", "aab"},
            {"(?<=(?>a))b", "ab"}, {"(?<=a\\X)b", "aeb"}, {"(?<!\\X)b", "ab"}, {"(?<=(?:a)*x)b", "aaxb"},
            {"(?<=(?:aa)*)b", "aab"}, {"(?<=(?:ab|cd))e", "cde"}, {"(?<=(?:ab|cd)+)e", "cde"},
            {"(?<=a|(?:bc)*)d", "bcd"}, {"(?<=a+b+)c", "abc"}, {"(?<=a{2,}b)c", "aabc"}, {"(?<=a*+b)c", "abc"},
            {"(?<=a*?b)c", "abc"}, {"(?<=\\Ra)b", "\nab"}, {"(?<=x(?:ab){0,2})c", "xabc"},
            {"(?<=x(?:a{2}){3})c", "xaaaaaac"}, {"(?<=(?:x|y)(?:a)*)b", "xab"}, {"(?<=(?:a)*(?:x|y))b", "axb"},
            {"(?<=(a|ab))c", "abc"}, {"(?<=(a+))b", "aab"}, {"(?<!(a)?)b", "ab"}, {"(?<=(?=b)a?)b", "ab"},
            {"(?<=\\X)*b", "ab"}, {"(?<!\\X)+b", "ab"}, {"(?<!a?b?.*)c", "c"}, {"(?<!a?b?.*)c", "xc"},
            {"(?<=\\X)\uD83D\uDE00", "a\uD83D\uDE00"}, {"(?<=\\X|\uD83D\uDE00)b", "\uD83D\uDE00b"},
            {"(?<=.)b", "\uD83D\uDE00b"}, {"(?<=(x)\\X)b|\\1", "xab"}, {"(?<=\\R)b", "\r\nb"},
            {"(?<=a{0,2}+)b", "aaab"}, {"(?<=(?<!a)b)c", "bc"}, {"(?<=a|bc*)d", "bccd"},
        };
        for (String[] t : lengths) m(t[0], t[1]);

        // Assertions repeated, and look-arounds left once they match.
        String[][] assertions = {
            {"(?=a)*b", "b"}, {"(?=a)+a", "a"}, {"(?<=a)?b", "b"}, {"(?!a){2}b", "b"}, {"^*a", "a"}, {"$?a", "a"},
            {"\\b+a", "a"}, {"\\A*a", "a"}, {"\\b{g}*a", "a"}, {"(?=(a))*a", "a"}, {"(?=(a))?a", "a"},
            {"(?=a)*+b", "b"}, {"(?=a){0}b", "b"}, {"x(?=a)*?a", "xa"}, {"(?m)^+a", "a"}, {"\\Z{2}a", "a"},
            {"(?=(a|ab))\\1c", "abc"}, {"(?<=(a|ba))\\1c", "baac"}, {"(?!(a|ab)x)\\w", "abc"},
        };
        for (String[] t : assertions) m(t[0], t[1]);

        // Every match: after an empty one, the next is looked for a character on.
        String[][] every = {
            {"(?=a)|a", "aa"}, {"\\b|a", "ab"}, {"x*", "axb"}, {"a*?", "aa"}, {"", "ab"}, {"(?<=a)", "aa"},
            {"a|ab", "aab"}, {"$|a", "a"}, {"(?=\\uD83D\\uDE00)|.", "\uD83D\uDE00a"},
        };
        for (String[] t : every) f(t[0], t[1]);

        // Grapheme clusters and their boundaries.
        for (String g : new String[] {"\\b{g}", "\\b{g", "\\b{x}", "\\b{gg}", "(?x)\\b {g}", "(?x)\\b{g }",
                "(?x)\\b{ g}", "[\\b{g}]", "\\B{g}", "[\\X]", "\\X{2}", "\\X+?", "(?i)\\X", "\\b{G}"}) p(g);
        for (String input : graphemeInputs()) {
            f("\\X", input);
            f("\\b{g}", input);
        }
        m("a\\b{g}b", "ab");
        m("\\X\\X", "\r\n\n");
        m("(\\X)\\1", "e\u0301e\u0301");
        m("\\X*+x", "abc");
        m("(?=\\X)\\X\\b{g}", "e\u0301x");

        // Word boundaries around marks.
        String[] marked = {
            "a\u0300", "\u0300", "\uD801\uDC00\u0300", "a\uD834\uDD67", "\u00E9\u0300", "1\u0300", "_\u0300",
            "\u0300a", "a\u0300\u0300b", "\uD801\uDC00\u0300a", "\u0663\u0300", " \u0300 ", "a \u0300",
            "\uD835\uDC00\u0300", "a\u0300\uD834\uDD67", "\u05D0\u05B0\u05B1x",
        };
        for (String input : marked) {
            f("\\b", input);
            f("(?U)\\b", input);
            if (input.chars().noneMatch(c -> Character.isSurrogate((char) c))) {
                f("\\B", input);
                f("(?U)\\B", input);
            }
        }

        System.out.print(OUT);
    }

    /// Every Unicode block that holds code points, in code point order.
    static List<Character.UnicodeBlock> blocksInOrder() {
        List<Character.UnicodeBlock> out = new ArrayList<>();
        for (int cp = 0; cp <= Character.MAX_CODE_POINT; cp++) {
            Character.UnicodeBlock b = Character.UnicodeBlock.of(cp);
            if (b != null && (out.isEmpty() || out.get(out.size() - 1) != b)) out.add(b);
        }
        return out;
    }

    static int[] blockRange(Character.UnicodeBlock b) {
        int lo = -1, hi = -1;
        for (int cp = 0; cp <= Character.MAX_CODE_POINT; cp++) {
            if (Character.UnicodeBlock.of(cp) == b) {
                if (lo < 0) lo = cp;
                hi = cp;
            }
        }
        return new int[] {lo, hi};
    }

    /// Texts to segment: every rule's case, written out, and a few hundred
    /// random strings over a character or two of each type.
    static List<String> graphemeInputs() {
        // One or two characters of each type (`Grapheme`'s numbering).
        int[][] of = {
            {'a', 0x10000}, {'\r'}, {'\n'}, {0x0001, 0xE0001}, {0x0300, 0x101FD}, {0x200D}, {0x1F1E6, 0x1F1FA},
            {0x0600, 0x110BD}, {0x0903, 0x11000}, {0x1100, 0xA960}, {0x1161, 0xD7B0}, {0x11A8, 0xD7CB}, {0xAC00},
            {0xAC01}, {0x00A9, 0x1F600},
        };
        int other = 0, cr = 1, lf = 2, control = 3, extend = 4, zwj = 5, ri = 6, prepend = 7, spacing = 8,
            l = 9, v = 10, t = 11, lv = 12, lvt = 13, pict = 14;
        int[][] written = {
            {cr, lf}, {lf, cr}, {cr, cr, lf}, {cr, extend}, {control, extend}, {prepend, control}, {prepend, cr},
            {prepend, prepend, other}, {prepend, prepend, extend}, {prepend}, {prepend, ri, ri, ri},
            {ri}, {ri, ri}, {ri, ri, ri}, {ri, ri, ri, ri}, {ri, ri, ri, ri, ri}, {ri, extend, ri}, {ri, zwj, ri},
            {ri, ri, extend, ri}, {other, ri, ri}, {pict, zwj, pict}, {pict, extend, zwj, pict},
            {pict, spacing, zwj, pict}, {other, zwj, pict}, {prepend, pict, zwj, pict}, {pict, zwj, zwj, pict},
            {pict, zwj, pict, zwj, pict}, {pict, pict}, {pict, extend, extend}, {zwj, pict}, {extend, zwj, pict},
            {l, l, v, t}, {lv, t, t}, {lvt, t}, {l, lv}, {l, lvt}, {v, t}, {t, t}, {lv, v, t}, {l, t}, {v, l},
            {t, v}, {lv, lv}, {l, l}, {l, extend}, {t, spacing}, {other, extend, extend}, {other, spacing},
            {spacing, spacing}, {extend}, {zwj}, {control, control}, {lf, lf}, {other, other},
        };
        List<String> out = new ArrayList<>();
        for (int[] types : written) {
            StringBuilder b = new StringBuilder();
            for (int type : types) b.appendCodePoint(of[type][0]);
            out.add(b.toString());
        }
        int[] sample = {0x102B, 0x0E33, 0x0EB3, 0xFF9E, 0x1F3FB, 0xE0020, 0x200C, 0x0378, 0xFFF9, 0x2028};
        for (int cp : sample) {
            out.add(new String(Character.toChars(cp)));
            out.add("a" + new String(Character.toChars(cp)) + "a");
        }
        Random random = new Random(57);
        for (int i = 0; i < 300; i++) {
            StringBuilder b = new StringBuilder();
            int n = 1 + random.nextInt(8);
            for (int j = 0; j < n; j++) {
                int[] cps = of[random.nextInt(of.length)];
                b.appendCodePoint(cps[random.nextInt(cps.length)]);
            }
            out.add(b.toString());
        }
        return out;
    }
}
