// Writes what owlmake's reading of `java.util.regex` (src/dosdp/java.rs) is
// built and checked against, from the running JDK:
//
//   tables  the Unicode block and script names `\p{In\u2026}`, `\p{block=\u2026}` and
//           `\p{script=\u2026}` take, as src/dosdp/java/names.rs;
//   cases   tests/fixtures/java-regex/cases.tsv: patterns, inputs and what
//           `Pattern` makes of them.
//
// Run through scripts/gen_java_regex.sh, which writes both.

import java.lang.reflect.Field;
import java.util.*;
import java.util.regex.*;

public class GenJavaRegex {
    public static void main(String[] args) throws Exception {
        if (args.length == 1 && args[0].equals("tables")) tables();
        else if (args.length == 1 && args[0].equals("cases")) cases();
        else throw new IllegalArgumentException("usage: tables | cases");
    }

    // \u2500\u2500 tables \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500

    @SuppressWarnings("unchecked")
    static void tables() throws Exception {
        Field mapField = Character.UnicodeBlock.class.getDeclaredField("map");
        mapField.setAccessible(true);
        Map<String, Character.UnicodeBlock> map = (Map<String, Character.UnicodeBlock>) mapField.get(null);
        Map<Character.UnicodeBlock, TreeSet<String>> names = new HashMap<>();
        for (Map.Entry<String, Character.UnicodeBlock> e : map.entrySet())
            names.computeIfAbsent(e.getValue(), k -> new TreeSet<>()).add(e.getKey());
        // Each block's code points, in code point order.
        LinkedHashMap<Character.UnicodeBlock, int[]> ranges = new LinkedHashMap<>();
        Character.UnicodeBlock prev = null;
        int start = 0;
        for (int cp = 0; cp <= Character.MAX_CODE_POINT + 1; cp++) {
            Character.UnicodeBlock b = cp <= Character.MAX_CODE_POINT ? Character.UnicodeBlock.of(cp) : null;
            if (b != prev) {
                if (prev != null) {
                    if (ranges.containsKey(prev)) throw new IllegalStateException(prev + " is not one range");
                    ranges.put(prev, new int[] {start, cp - 1});
                }
                prev = b;
                start = cp;
            }
        }
        Field aliasField = Character.UnicodeScript.class.getDeclaredField("aliases");
        aliasField.setAccessible(true);
        Map<String, Character.UnicodeScript> aliases = (Map<String, Character.UnicodeScript>) aliasField.get(null);

        StringBuilder out = new StringBuilder();
        out.append("// Generated by scripts/gen_java_regex.sh from Java ")
           .append(System.getProperty("java.version")).append(". Do not edit.\n\n");
        out.append("/// A Unicode block: every name it goes by in `\\p{InName}` and\n");
        out.append("/// `\\p{block=Name}`, in upper case, and the code points it holds (none for\n");
        out.append("/// a block that holds none).\n");
        out.append("pub(super) type Block = (&'static [&'static str], Option<(u32, u32)>);\n\n");
        out.append("/// Every Unicode block.\n");
        out.append("pub(super) const BLOCKS: &[Block] = &[\n");
        List<Character.UnicodeBlock> order = new ArrayList<>(ranges.keySet());
        for (Character.UnicodeBlock b : names.keySet()) if (!ranges.containsKey(b)) order.add(b);
        for (Character.UnicodeBlock b : order) {
            out.append("    (&[");
            boolean first = true;
            for (String n : names.get(b)) {
                out.append(first ? "" : ", ").append('"').append(n).append('"');
                first = false;
            }
            int[] r = ranges.get(b);
            if (r == null) out.append("], None),\n");
            else out.append(String.format("], Some((0x%04X, 0x%04X))),\n", r[0], r[1]));
        }
        out.append("];\n\n");
        out.append("/// Each script `\\p{IsName}` and `\\p{script=Name}` name: its name, and the\n");
        out.append("/// other names it goes by, in upper case.\n");
        out.append("pub(super) const SCRIPTS: &[(&str, &[&str])] = &[\n");
        for (Character.UnicodeScript s : Character.UnicodeScript.values()) {
            out.append("    (\"").append(s.name()).append("\", &[");
            boolean first = true;
            for (String a : new TreeSet<>(aliasesOf(aliases, s))) {
                out.append(first ? "" : ", ").append('"').append(a).append('"');
                first = false;
            }
            out.append("]),\n");
        }
        out.append("];\n");
        System.out.print(out);
    }

    static List<String> aliasesOf(Map<String, Character.UnicodeScript> aliases, Character.UnicodeScript s) {
        List<String> out = new ArrayList<>();
        for (Map.Entry<String, Character.UnicodeScript> e : aliases.entrySet())
            if (e.getValue() == s) out.add(e.getKey());
        return out;
    }

    // \u2500\u2500 cases \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500

    /// What a case line holds, after its kind: `P` a pattern and whether
    /// `find` matches each probe, a bit per probe in order, four to a hex
    /// digit, most significant first; or `E` where the pattern is refused; `D` the same over each probe written twice; `M` a
    /// pattern, an input and the first match's group spans in UTF-16 units
    /// (`-` for a group that took no part), or `N` or `E`; `R` a pattern, an
    /// input, a replacement and `replaceFirst`'s result, or `E`.
    static final StringBuilder OUT = new StringBuilder();

    /// The probes: characters whose properties and case mappings are the
    /// same in every Unicode version since 15.0.
    static final String[] PROBES = {
        "a", "A", "z", "Z", "k", "K", "s", "S", "i", "I", "0", "9", "_", "-", "$", " ", "\t", "\n",
        "\u000B", "\r", "\u0007", "\u001B", "\u001C", "\u007F", "\u0085", "\u009F", "\u00A0", "\u00A2",
        "\u00AA", "\u00AD", "\u00B2", "\u00B5", "\u00C5", "\u00DF", "\u00E5", "\u00E9", "\u00C9", "\u00F7",
        "\u00FF", "\u0130", "\u0131", "\u0178", "\u017F", "\u01C4", "\u01C5", "\u01C6", "\u02B0", "\u0300",
        "\u0345", "\u0370", "\u0378", "\u0391", "\u0399", "\u039C", "\u03A3", "\u03B1", "\u03B9", "\u03BC",
        "\u03C2", "\u03C3", "\u0410", "\u05D0", "\u0663", "\u0903", "\u0F3A", "\u16EE", "\u1E9E", "\u1F80",
        "\u1F88", "\u1FB3", "\u1FBC", "\u1FBE", "\u200B", "\u200C", "\u2007", "\u2028", "\u2029", "\u202F",
        "\u2060", "\u2126", "\u212A", "\u212B", "\u2160", "\u2E2F", "\u3000", "\u3007", "\u4E2D", "\uE000",
        "\uFDD0", "\uFF10", "\uFF21", "\uFFFD", "\uFFFF", "\uD835\uDC00", "\uD83D\uDE00", "\uD83C\uDFFB",
        "\uD801\uDC00", "\uD801\uDC28", "\uDB40\uDC01", "\uDB80\uDC00", "\uDBFF\uDFFF",
    };

    static String esc(String s) {
        StringBuilder b = new StringBuilder();
        for (char c : s.toCharArray()) {
            if (c < 0x20 || c > 0x7e || c == '\\') b.append(String.format("\\u%04x", (int) c));
            else b.append(c);
        }
        return b.toString();
    }

    static void probe(String kind, String pattern, boolean twice) {
        Pattern p;
        try {
            p = Pattern.compile(pattern);
        } catch (PatternSyntaxException e) {
            OUT.append(kind).append('\t').append(esc(pattern)).append("\tE\n");
            return;
        }
        StringBuilder bits = new StringBuilder();
        for (int i = 0; i < PROBES.length; i += 4) {
            int nibble = 0;
            for (int j = i; j < i + 4; j++) {
                boolean found = j < PROBES.length && p.matcher(twice ? PROBES[j] + PROBES[j] : PROBES[j]).find();
                nibble = nibble << 1 | (found ? 1 : 0);
            }
            bits.append(Character.forDigit(nibble, 16));
        }
        OUT.append(kind).append('\t').append(esc(pattern)).append('\t').append(bits).append('\n');
    }

    static void p(String pattern) { probe("P", pattern, false); }
    static void d(String pattern) { probe("D", pattern, true); }

    static void m(String pattern, String input) {
        OUT.append("M\t").append(esc(pattern)).append('\t').append(esc(input)).append('\t');
        Pattern p;
        try {
            p = Pattern.compile(pattern);
        } catch (PatternSyntaxException e) {
            OUT.append("E\n");
            return;
        }
        Matcher m = p.matcher(input);
        if (!m.find()) {
            OUT.append("N\n");
            return;
        }
        for (int g = 0; g <= m.groupCount(); g++) {
            OUT.append(g == 0 ? "" : ";");
            OUT.append(m.start(g) < 0 ? "-" : m.start(g) + "," + m.end(g));
        }
        OUT.append('\n');
    }

    static void r(String pattern, String input, String replacement) {
        OUT.append("R\t").append(esc(pattern)).append('\t').append(esc(input)).append('\t')
           .append(esc(replacement)).append('\t');
        try {
            OUT.append(esc(input.replaceFirst(pattern, replacement))).append('\n');
        } catch (RuntimeException e) {
            OUT.append("E\n");
        }
    }

    static void cases() {
        OUT.append("# Generated by scripts/gen_java_regex.sh from Java ")
           .append(System.getProperty("java.version")).append(". Do not edit.\n");
        OUT.append("# probes");
        for (String probe : PROBES) OUT.append('\t').append(esc(probe));
        OUT.append('\n');

        // Character properties, as each prefix and flag reads them.
        String[] names = {
            "L", "Lu", "Ll", "Lt", "Lm", "Lo", "M", "Mn", "Mc", "Me", "N", "Nd", "Nl", "No", "P", "Pc", "Pd",
            "Ps", "Pe", "Pi", "Pf", "Po", "S", "Sm", "Sc", "Sk", "So", "Z", "Zs", "Zl", "Zp", "C", "Cc", "Cf",
            "Co", "Cs", "Cn", "LC", "LD", "L1", "all", "ASCII", "Alnum", "Alpha", "Blank", "Cntrl", "Digit",
            "Graph", "Lower", "Print", "Punct", "Space", "Upper", "XDigit", "javaLowerCase", "javaUpperCase",
            "javaWhitespace", "javaMirrored", "javaAlphabetic", "javaIdeographic", "javaTitleCase", "javaDigit",
            "javaDefined", "javaLetter", "javaLetterOrDigit", "javaJavaIdentifierStart",
            "javaJavaIdentifierPart", "javaUnicodeIdentifierStart", "javaUnicodeIdentifierPart",
            "javaIdentifierIgnorable", "javaSpaceChar", "javaISOControl", "IsL", "IsLu", "IsLatin", "IsGreek",
            "IsAlphabetic", "IsLetter", "IsLowercase", "IsUppercase", "IsTitlecase", "IsPunctuation",
            "IsControl", "IsWhite_Space", "IsWhiteSpace", "IsDigit", "IsHex_Digit", "IsHexDigit",
            "IsJoin_Control", "IsJoinControl", "IsNoncharacter_Code_Point", "IsNoncharacterCodePoint",
            "IsAssigned", "IsIdeographic", "IsEmoji", "IsEmoji_Presentation", "IsEmoji_Modifier",
            "IsEmoji_Modifier_Base", "IsEmoji_Component", "IsExtended_Pictographic", "IsWord", "IsAlnum",
            "IsAlpha", "IsLower", "IsUpper", "IsSpace", "IsPunct", "IsXDigit", "IsCntrl", "IsBlank",
            "IsGraph", "IsPrint", "IsjavaLowerCase", "isLatin", "ISLATIN", "IsLATIN", "Islatin", "Isgreek",
            "IsCommon", "IsInherited", "IsUnknown", "IsHan", "IsCyrillic", "IsArabic", "IsZyyy", "IsZinh",
            "IsZzzz", "IsGrek", "IsHani", "IsASCII", "IsAll", "IsLL", "Isll", "Is_Lu", "IsCased", "IsDash",
            "IsMath", "IsRadical", "IsLu ", "Is Lu", "Greek", "Latin", "Alphabetic", "Lowercase", "Uppercase",
            "White_Space", "Letter", "Punctuation", "Ideographic", "lu", "LU", "l", "alpha", "ALPHA", "lower",
            "LOWER", "punct", "javalowercase", "script=Greek", "sc=Greek", "sc=Grek", "script=GREEK",
            "sc=latin", "script=Latn", "Script=Greek", "SC=Greek", "sc=Common", "sc=Zyyy", "sc=Inherited",
            "sc=Unknown", "sc=Zzzz", "sc=Old_Italic", "sc=OldItalic", "sc=Old Italic", "sc=Han", "sc=Hani",
            "sc=Hira", "sc=Nko", "sc=Signwriting", "sc=Hrkt", "sc=Qaai", "sc=", "gc=Lu", "general_category=Lu",
            "gc=L", "gc=LC", "GC=Lu", "gc=lu", "General_Category=Lu", "gc=Upper", "gc=Lower", "gc=all",
            "gc=javaLowerCase", "block=Greek", "blk=Greek", "blk=GreekandCoptic", "block=Greek and Coptic",
            "blk=GREEK_AND_COPTIC", "blk=greek", "Block=Greek", "BLK=Greek", "InGreek", "InGreekandCoptic",
            "InGreek and Coptic", "InGREEK_AND_COPTIC", "Ingreek", "INGreek", "inGreek", "InBasicLatin",
            "InBasic_Latin", "InBasic Latin", "InLatin-1 Supplement", "InLatin1Supplement",
            "InLatin-1Supplement", "InLATIN_1_SUPPLEMENT", "InCombiningDiacriticalMarks", "InGreekExtended",
            "InLetterlikeSymbols", "InCJKUnifiedIdeographs", "InArabic", "InCombiningMarksforSymbols",
            "InCombining Diacritical Marks for Symbols", "InCyrillicSupplementary", "InCyrillicSupplement",
            "InCyrillic Supplement", "InEmoticons", "InHighSurrogates", "InLow_Surrogates",
            "InSurrogates_Area", "InSpecials", "InPrivateUseArea", "InPrivate Use Area",
            "InSupplementary_Private_Use_Area_A", "InSupplementaryPrivateUseArea-B", "InTags",
            "InMathematicalAlphanumericSymbols", "InDeseret", "InHalfwidth_and_Fullwidth_Forms",
            "InGeneralPunctuation", "InNoSuchBlock", "In", "Is", "Is L", "L&", "",
        };
        for (String n : names) {
            p("\\p{" + n + "}");
            p("\\P{" + n + "}");
            p("(?i)\\p{" + n + "}");
            p("(?U)\\p{" + n + "}");
            p("[x\\p{" + n + "}]");
            p("[^x\\P{" + n + "}]");
            p("(?iu)[\\p{" + n + "}]");
        }
        for (String n : new String[] {"L", "N", "M", "P", "S", "Z", "C", "l", "u", "X", "{", "}"}) {
            p("\\p" + n);
            p("\\P" + n);
            p("[\\p" + n + "]");
        }
        p("\\p");
        p("\\p{L");
        p("[\\p{L]");

        // Literals, classes and ranges under each case flag.
        String[] chars = {
            "a", "A", "k", "K", "s", "S", "i", "I", "\u00B5", "\u00C5", "\u00DF", "\u00E5", "\u00E9",
            "\u00FF", "\u0130", "\u0131", "\u0178", "\u017F", "\u01C4", "\u01C5", "\u01C6", "\u0345", "\u0391",
            "\u0399", "\u039C", "\u03A3", "\u03B1", "\u03B9", "\u03BC", "\u03C2", "\u03C3", "\u1E9E", "\u1F80",
            "\u1F88", "\u1FB3", "\u1FBC", "\u1FBE", "\u2126", "\u212A", "\u212B", "\u2160", "\uD801\uDC00",
            "\uD801\uDC28", "5", "_", "$",
        };
        for (String c : chars) {
            String q = c.equals("$") ? "\\$" : c;
            for (String flags : new String[] {"", "(?i)", "(?iu)", "(?u)", "(?U)", "(?i)(?-i)"}) {
                p(flags + q);
                d(flags + q + q);
                p(flags + "[" + q + "]");
                p(flags + "[^" + q + "]");
                p(flags + String.format("\\x{%X}", c.codePointAt(0)));
                d(flags + String.format("\\x{%X}\\x{%X}", c.codePointAt(0), c.codePointAt(0)));
                p(flags + String.format("[\\x{%X}]", c.codePointAt(0)));
            }
        }
        String[] ranges = {
            "a-z", "A-Z", "Z-a", "a-k", "k-s", "\\x41-\\x5A", "\\x41-Z", "A-\\x5A", "\\u00C0-\\u00FF", "\\u00DF-\\u00FF",
            "\\u00B5-\\u00B5", "\\u0370-\\u03FF", "\\u0390-\\u03A9", "\\u1F80-\\u1F8F", "\\u1FB0-\\u1FBF",
            "\\u2100-\\u214F", "\\u0100-\\u017F", "\\u0130-\\u0131", "\\u01C4-\\u01C6", "\\x{10400}-\\x{1044F}",
            "\\uD800-\\uDFFF", "\\uD7FF-\\uE000", "\\x00-\\x{10FFFF}", "0-9", "!-/", "z-a", "a-\\w", "a-\\p{L}",
        };
        for (String r : ranges) {
            for (String flags : new String[] {"", "(?i)", "(?iu)"}) {
                p(flags + "[" + r + "]");
                p(flags + "[^" + r + "]");
            }
        }

        // Class syntax.
        String[] classes = {
            "[a-]", "[-a]", "[a-[b]]", "[a-[\\d]]", "[\\w-]", "[\\w-a]", "[a&&b]", "[a-z&&[^aeiou]]",
            "[a-z&&k-s&&s]", "[\\p{L}&&\\p{Lu}]", "[^\\p{L}&&\\p{Lu}]", "[a[b]]", "[^a[b]]", "[[a]&&[b]]",
            "[a&&]", "[&&a]", "[a&b]", "[a&&&b]", "[]a]", "[^]a]", "[\\]]", "[\\[]", "[\\Qa-z\\E]",
            "[\\Q]\\E]", "[x\\Q\\E]", "[\\t-\\r]", "[\\0101-\\0132]", "[\\cA-\\cZ]", "[\\u0041-\\u005A]",
            "[\\x{41}-\\x{5A}]", "[\\1]", "[\\k]", "[\\b]", "[\\h]", "[\\v]", "[\\H]", "[\\V]", "[\\R]",
            "[\\s\\S]", "[\\d\\w]", "[\\D]", "[\\W]", "[a-z-0]", "[$-a]", "(?x)[a - z]", "(?x)[ a ]",
            "(?x)[a#]\n]", "[a", "[", "[]", "[^]", "[\\]", "[a-z\\]", "[\\uD83D\\uDE00]", "[\\uD800]",
            "[\\x{D800}]", "[\\x{110000}]", "[\\N{LATIN SMALL LETTER A}]",
        };
        for (String c : classes) {
            for (String flags : new String[] {"", "(?i)", "(?iu)", "(?U)"}) p(flags + c);
        }

        // Escapes, quotation and comments.
        String[] escapes = {
            "\\t", "\\n", "\\r", "\\f", "\\a", "\\e", "\\0101", "\\0", "\\08", "\\0377", "\\0400", "\\x41",
            "\\x4", "\\x{41}", "\\x{}", "\\x{110000}", "\\u0041", "\\u004", "\\uD83D\\uDE00", "\\uD83D",
            "\\uDE00", "\\uD83D\\u0041", "\\cA", "\\c", "\\c?", "\\w", "\\W", "\\d", "\\D", "\\s", "\\S",
            "\\h", "\\H", "\\v", "\\V", "\\R", "\\X", "\\N{LATIN SMALL LETTER A}", "\\b", "\\B", "\\A",
            "\\G", "\\Z", "\\z", "\\E", "\\Q", "\\Qa\\E", "\\Qa-z\\E", "\\Q\\E", "\\Q\\", "\\Q\\\\E",
            "\\Qa\\Eb", "\\Q1\\E", "\\x\\Q1\\E", "\\Q.*\\E", "a\\Q\\E*", "\\Qab\\E*", "\\-", "\\.", "\\\u00E9",
            "\\ ", "\\y", "\\i", "\\j", "\\l", "\\m", "\\o", "\\q", "\\g", "\\K", "\\L", "\\U", "\\T",
            "\\1", "\\k<a>",
        };
        for (String e : escapes) {
            for (String flags : new String[] {"", "(?i)", "(?iu)", "(?U)"}) p(flags + e);
        }
        String[] comments = {
            "(?x)a b", "(?x)a b*", "(?x)ab *", "(?x)a#x\nb", "(?x)a#x\u2028b", "(?x)a#x\u0085b", "(?x)a\u00A0",
            "(?x)a\u2028", "(?x)a\\ b", "(?x)[ ]", "(?x)\\p{ L }", "(?x)a{ 2 }", "(?x)( a )", "(?x)a#",
            "(?x)(?-x)a b", "(?x:a b)c d", "(?xd)a#x\u2028b", "(?x)a\u000Bb", "(?x)a\u000Cb",
        };
        for (String c : comments) p(c);

        // Matches, with groups.
        String[][] matches = {
            {"^(\\w+)\\s(\\d+)$", "abc 123"}, {"^(\\w+)\\s(\\d+)$", "\u00E9 1"}, {"a$", "a\n"},
            {"a$", "a\r\n"}, {"a$", "a\u0085"}, {"a$", "a\u2028"}, {"a$", "a\n\n"}, {"(?m)a$", "a\nb"},
            {"(?m)^b", "a\nb"}, {"(?m)^b", "a\r\nb"}, {"(?m)^b", "a\rb"}, {"(?m)^", "a\n"},
            {"(?m)$", "a\r\n"}, {"(?d)a$", "a\r\n"}, {"(?d)(?m)^b", "a\rb"}, {"a.b", "a\rb"},
            {"a.b", "a\u2028b"}, {"(?s)a.b", "a\nb"}, {"(?d)a.b", "a\rb"}, {"a\\Z", "a\r\n"},
            {"a\\z", "a\n"}, {"\\Aa", "ba"}, {"\\Ga", "ba"}, {"\\b\u00E9", "\u00E9"}, {"(?U)\\b\u00E9", "\u00E9"},
            {"a*+a", "aaa"}, {"(?>a*)a", "aaa"}, {"(?<=x)(a)\\1", "xaa"}, {"(?<!x)a", "xa a"},
            {"(a)|(b)", "b"}, {"(a)?b", "b"}, {"(?<n>a)\\k<n>", "aa"}, {"(a)\\2", "aa"}, {"(a)\\11", "aa1"},
            {"(a)(b)(c)(d)(e)(f)(g)(h)(i)(j)\\10", "abcdefghijj"}, {"(?i)(a)\\1", "aA"},
            {"(?i)(\u00E9)\\1", "\u00E9\u00C9"}, {"(?iu)(\u00E9)\\1", "\u00E9\u00C9"}, {"(?i)\u00E9", "\u00C9"},
            {"(?iu)\u00E9", "\u00C9"}, {"(?i)[a-c]", "B"}, {"a{2}", "aaa"}, {"a{2,}", "aaa"}, {"a{,2}", "aaa"},
            {"a{2,1}", "aaa"}, {"a{", "a{"}, {"a{x", "a{x"}, {"{", "{"}, {"}", "}"}, {"]", "]"}, {"x*?", "xx"},
            {"(?:ab)+", "abab"}, {"\\d+", "\u0663\u0661"}, {"(?U)\\d+", "\u0663\u0661"}, {"\\w", "\u00E9"},
            {"(?U)\\w", "\u00E9"}, {"\\s", "\u00A0"}, {"(?U)\\s", "\u00A0"}, {"\\h", "\u00A0"},
            {"\\v", "\u2028"}, {"\\R", "\r\n"}, {"[a-z]+", "\uD83D\uDE00abc"}, {".", "\uD83D\uDE00"},
            {"\\uD83D\\uDE00", "x\uD83D\uDE00"}, {"\\p{L}+", "a\u00E9\u4E2D1"}, {"\\Qa.b\\E", "axb a.b"},
            {"(?i)\\x41", "a"}, {"(?i)\u00DFa", "\u1E9Ea"}, {"(?iu)\u00DF", "\u1E9E"},
            {"(?iu)\u00DFa", "\u1E9EA"}, {"(?iu)[\u00DF]", "\u1E9E"}, {"(?iu)k", "\u212A"},
            {"(?iu)[k]", "\u212A"}, {"(?iu)[a-z]", "\u212A"}, {"(?i)[a-z]", "\u212A"},
            {"(?iu)\u03C3+", "\u03A3\u03C2\u03C3"}, {"(?iu)[\u03C3]+", "\u03A3\u03C2\u03C3"},
            {"(?iu)(k)\\1", "k\u212A"}, {"(?iu)ss", "\u017F\u017F"}, {"(?iu)\u00DF+", "\u1E9E\u00DF"},
            {"(?iu)a\u00DF+", "a\u1E9E"}, {"(?iu)\u00DFa+", "\u1E9Eaa"}, {"(?x)(?iu)\u00DF a", "\u1E9Ea"},
            {"(?iu)\u00DF\\x{DF}", "\u1E9E\u1E9E"}, {"(?iu)\u00DF\\Q\\E\u00DF", "\u1E9E\u1E9E"},
            {"(?iu)[\u00DF-\u00DF]", "\u1E9E"}, {"(?iu)[\u00DE-\u00DF]", "\u1E9E"}, {"", ""},
            {"", "abc"}, {"a|", "b"}, {"|a", "a"}, {"()", "a"}, {"(?=a)", "a"}, {"(?!)", "a"},
            {"(", "a"}, {")", "a"}, {"(?", "a"}, {"(?<", "a"}, {"(?<1a>a)", "a"}, {"(?<a>a)(?<a>b)", "ab"},
            {"(?q)a", "a"}, {"(?i-i)a", "A"}, {"(?i:a)a", "AA"}, {"(?i:a)a", "Aa"}, {"((?i)a)a", "AA"},
            {"((?i)a)a", "Aa"}, {"a**", "aa"}, {"a*?+", "aa"}, {"a?+a", "a"}, {"*a", "a"}, {"a{1}{2}", "aa"},
        };
        for (String[] t : matches) m(t[0], t[1]);

        // Replacements.
        String[][] replacements = {
            {"(\\w+) (\\w+)", "ab cd", "$2 $1"}, {"(a)", "a", "$12"}, {"(a)", "a", "$2"}, {"(a)", "a", "\\$1"},
            {"(a)", "a", "\\\\"}, {"(a)", "a", "x\\"}, {"(a)", "a", "$"}, {"(a)", "a", "${x}"},
            {"(?<x>a)", "a", "${x}${x}"}, {"(?<x>a)", "a", "${1}"}, {"(a)|(b)", "b", "[$1][$2]"},
            {"x", "abc", "y"}, {"", "abc", "-"}, {"b*", "abc", "-"}, {"(a)(b)(c)(d)(e)(f)(g)(h)(i)(j)(k)", "abcdefghijk", "$11$10$1"},
        };
        for (String[] t : replacements) r(t[0], t[1], t[2]);

        System.out.print(OUT);
    }
}
