//! The build plan: what owlmake executes, and the only description of a build.
//!
//! A plan says which artefacts and import modules to produce, and the steps that
//! produce them. It is generated by an ingest (today [`crate::odk`], which resolves
//! a repo's pre-existing build files) or read straight from a committed
//! `owlmake.yaml` ([`crate::spec`]) — and once it exists nothing else is consulted:
//! the executor ([`crate::build`]) has no route back to whatever produced it.

pub mod gaps;
pub mod step;

use std::fmt;

pub use step::{Op, Step};
use step as robot;

/// The plan for one release artefact (e.g. `oba-full.owl`).
pub struct ArtefactPlan {
    pub target: String,
    /// First prerequisite (`$<`) — the pipeline input.
    pub input: Option<String>,
    /// Every prerequisite of the rule (normal and order-only), so execution can
    /// apply the dependency rule: a prerequisite is built only when something that
    /// actually needs it is missing. Without the edges the executor would build
    /// every planned prerequisite whose file happens to be absent — re-mirroring
    /// every upstream ontology even though the committed `merged_import.owl` they
    /// feed is already present.
    pub needs: Vec<String>,
    /// Which of `needs` are ORDER-ONLY (`target: normal | order-only`).
    ///
    /// An order-only prerequisite says when a rule may run, never whether it must:
    /// it is built first if it is missing, and its age is never compared with the
    /// target's. uPheno's component stamps are `tmp/stamp-component-<x>.owl:
    /// | $(TMPDIR)`, and `tmp/` is touched by every file written into it — so
    /// comparing it would leave each stamp older than its own directory, rebuild
    /// all nine components, and carry that through the source merge, the import
    /// seed and the 44 MB merged import on every build.
    pub order_only: Vec<String>,
    pub steps: Vec<Step>,
    pub gaps: Vec<String>,
    /// Set when no rule for the target was found.
    pub missing_rule: bool,
    /// Where the recipe sends its console output. A check whose rule ends
    /// `… > $@` builds its target out of what the tool prints, so the file exists
    /// (empty, when nothing was printed) exactly if the recipe ran to the end.
    /// Recorded because the target is otherwise unaccounted for: the steps
    /// themselves name only the intermediates they write.
    pub stdout_file: Option<String>,
    /// What this target is built by under the OTHER value of a switch.
    ///
    /// A conditional is resolved once, at plan time, so `steps` above is the
    /// recipe of the branch that was taken. Where the branch NOT taken defines
    /// its own recipe for the same target, it is recorded here and a run that
    /// flips the switch uses it — the plan describes the build under every value
    /// of the switch, not the one ingest happened to see.
    ///
    /// Empty is the ordinary case and means what it says: the other branch
    /// defines no rule at all, so under that value the target is not built and
    /// the file on disk stands. That is the `refresh_groups` pin, and the two
    /// answers coexist per TARGET — one switch may pin some of its targets and
    /// supply a different recipe for others, which is exactly what UBERON's `BRI`
    /// does.
    pub branches: Vec<Branch>,
}

/// One target's pipeline under a particular value of one switch.
#[derive(Clone, Debug)]
pub struct Branch {
    /// The switch this pipeline belongs to (`BRI`).
    pub flag: String,
    /// The value of that switch which selects it (`false`).
    pub value: String,
    /// `$<` for this branch's own rule.
    pub input: Option<String>,
    /// This branch's own prerequisites — a branch commonly has fewer, which is
    /// the point of it: UBERON's `BRI=false` bridges stamp depends on nothing.
    pub needs: Vec<String>,
    pub steps: Vec<Step>,
}

/// The plan for one import product.
pub struct ImportPlan {
    pub id: String,
    /// Upstream source / mirror URL (the pipeline input is this ontology).
    pub source: String,
    /// Output module path, relative to `src/ontology` (`imports/<id>_import.owl`).
    pub output: String,
    /// The mirror→module pipeline: the operations that turn the source ontology
    /// into the committed import module (`extract`/`filter`/`remove`/`rename`/…),
    /// resolved at ingest from the repo's own rule (or synthesized from the import
    /// product's flags when the repo declares no explicit recipe). Seed/exclude
    /// term files are resolved to their committed *sources* (e.g.
    /// `iri_dependencies/`) at generation time, so execution never re-guesses a
    /// path.
    pub steps: Vec<Step>,
    pub cached: bool,
    pub gaps: Vec<String>,
    /// The import product behind this module (mirror URL/type, base-IRI flags,
    /// `is_large`), resolved at ingest. Recorded so an `--imports fresh` run
    /// re-mirrors from the plan and nothing else.
    pub product: Option<crate::odk::ImportProduct>,
    /// The `mirror-<id>` / `mirror/<id>.owl` steps for a custom mirror — a project
    /// script owlmake cannot synthesize from the product's flags.
    pub mirror_steps: Vec<Step>,
    /// The FILES those steps read that another rule makes.
    ///
    /// A mirror recipe usually fetches its own input, and that fetch is one of
    /// `mirror_steps`. Two of MONDO's do not: `mirror-hgnc` merges
    /// `mirror/hgnc_gene.nt` and `mirror-ncbigene` queries over
    /// `mirror/ncbi_gene.nt`, and each `.nt` is made by a rule of its own (a
    /// `curl … | gzip -d`, 74 MB and 3.2 GB). Recorded here because the plan must
    /// name every path the build reads: without it the executor reaches a pipeline
    /// with nothing to feed it, and a plan-only repo has nothing else left to
    /// re-read the prerequisite from.
    pub mirror_inputs: Vec<String>,
}

impl ImportPlan {
    /// The seed term-file path(s) this import extracts over — the `--term-file`
    /// arguments of its first `extract`/`filter` step. Used for the human stage
    /// description ("…terms listed in <file>…") and the merged-import seed union.
    pub fn seed_term_files(&self) -> Vec<String> {
        for step in &self.steps {
            let tf: Vec<String> = match step {
                Step::Op(robot::Op::Extract { term_files, .. }) => term_files.clone(),
                Step::Op(robot::Op::Filter(spec)) => spec.term_files.clone(),
                _ => continue,
            };
            if !tf.is_empty() {
                return tf;
            }
        }
        Vec::new()
    }

    /// The module-reduction strategy name for display (`BOT`/`STAR`/`TOP`/`MIREOT`),
    /// taken from the first `extract` step, else `"filter"`/`"copy"`.
    pub fn method(&self) -> &str {
        for step in &self.steps {
            match step {
                Step::Op(robot::Op::Extract { method, .. }) => return method,
                Step::Op(robot::Op::Filter(_)) => return "filter",
                _ => {}
            }
        }
        "copy"
    }
}

/// How fresh a target group's outputs must be for this run.
#[derive(Clone, Copy, PartialEq, Eq, Debug, serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[serde(rename_all = "lowercase")]
pub enum Freshness {
    /// Reuse the outputs that are present (`--keep <group>`).
    Keep,
    /// Rebuild them even when present (`--rebuild <group>`).
    Rebuild,
}

/// One rebuild switch the plan exposes.
#[derive(Clone, Debug, serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct RefreshGroup {
    /// How `--rebuild <name>` / `--keep <name>` spells it.
    pub name: String,
    /// The build-configuration variable that switches this group — `MIR` for the
    /// mirrors, `BRI` for UBERON's bridges. A run spells the same request either
    /// way (`BRI=false` or `--keep bridges`), and recording the variable is what
    /// lets a repository with no build configuration left still answer to the
    /// spelling its own CI and its own recipes use.
    ///
    /// Empty for a hand-authored group that no configuration variable switches:
    /// `--rebuild <name>` / `--keep <name>` still reach it, and no assignment
    /// does.
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub flag: String,
    /// The plan targets this group covers, in the plan's own spelling. Names, not
    /// rules: `--rebuild imports` resolves them from the plan exactly as
    /// `om make <target>` would.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub targets: Vec<String>,
    /// What this group does when the run says nothing.
    pub default: Freshness,
}

/// How every string in a plan refers to the run's release version.
///
/// The version is a run input, so it is written down ONCE — in [`Plan::version`]
/// — and every ontology IRI, `owl:versionInfo` literal and recipe word that
/// needs it holds this reference instead of a copy. A build resolves the field
/// and substitutes; a plan carrying the date expanded into all ninety-odd of
/// them would release the same dated artefacts forever.
pub const VERSION_REF: &str = "{version}";

/// The value of [`Plan::version`] for a repo whose release version is the date
/// the build runs. A configuration that pins a literal version records that
/// literal instead, and either way the run may override it.
pub const VERSION_TODAY: &str = "{today}";

/// Whether a switch's value reads as ON. The spellings a build configuration and
/// a command line use between them, in one place, so a `BRI=1` means what a
/// `BRI=true` means wherever the question is asked.
pub fn is_on(value: &str) -> bool {
    matches!(value.trim().to_ascii_lowercase().as_str(), "true" | "1" | "yes" | "on")
}

/// The release version this run stamps: what the caller asked for, else the
/// plan's default — and [`VERSION_TODAY`] resolves to today's date, which is
/// what a repo that releases under the build date means by it.
pub fn release_version(plan_default: &str, requested: Option<&str>) -> String {
    match requested {
        Some(v) => v.to_string(),
        None if plan_default == VERSION_TODAY => today(),
        None => plan_default.to_string(),
    }
}

/// Today's date, `YYYY-MM-DD`.
pub fn today() -> String {
    // Avoid a date dependency: shell out to `date`.
    std::process::Command::new("date")
        .arg("+%Y-%m-%d")
        .output()
        .ok()
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| "unknown".into())
}

pub struct Plan {
    pub id: String,
    /// The release version to stamp, as a DEFAULT: a literal the build
    /// configuration pins, or `{today}` for a repo that releases under the date
    /// of the build. Every other string that needs the version holds `{version}`,
    /// a reference to this field, and a run binds the two together — so the same
    /// plan releases on any date without being regenerated.
    pub version: String,
    pub ontology_iri: String,
    pub reasoner: String,
    pub use_base_merging: bool,
    pub exclude_iri_patterns: Vec<String>,
    /// How `extract --individuals` treats individuals in a locality-based module:
    /// `include` (default), `minimal`, `definitions`, or `exclude`. Applied when
    /// building the merged import so, e.g., ECTO's `exclude` drops imported
    /// individuals.
    pub slme_individuals: Option<String>,
    pub imports: Vec<ImportPlan>,
    pub merged_import: Option<String>,
    pub components: Vec<String>,
    /// Build variables the *executor* still needs after planning — `$(SRC)`,
    /// `$(OTHER_SRC)`, `$(ROBOT)`, `$(OBOBASE)`, `$(MIRRORDIR)` — resolved at
    /// ingest. Recorded here (and so in `owlmake.json`) because a recorded step
    /// expands them while it RUNS, not while the plan is built: without them a
    /// plan-only repo silently loses the edit file's sibling sources from the
    /// source merge and the merged-import seed, and writes its mirrors where its
    /// own steps do not look. Output SHAPE is not decided here — the two
    /// version-dependent byte behaviours read `emulate_robot_version`.
    pub variables: std::collections::BTreeMap<String, String>,
    /// Gaps in the repo's own rules that *build* declared components (e.g.
    /// uPheno's `python3 upheno_build.py …`): steps owlmake can't reproduce.
    /// Empty when components are shipped pre-built (nothing to build).
    pub component_gaps: Vec<String>,
    /// Generated files the artefacts and imports depend on (`all_robot_plugins`,
    /// `tmp/simple_seed.txt`, `subsets/<x>-tags.ofn`, generated components, …),
    /// resolved at plan time and recorded here so execution never has to consult
    /// anything else. In dependency order: deepest first.
    pub prerequisites: Vec<ArtefactPlan>,
    pub artefacts: Vec<ArtefactPlan>,
    /// What to build when no target is named. Resolved at plan time from the
    /// repo's default goal, so a plan-only repo still knows what a bare build
    /// means: EFO's `all` is `all_imports all_gwas all_components release qc`, so
    /// a build that stopped at the release artefacts would skip the QC that ships
    /// with them.
    pub default_targets: Vec<String>,
    /// The edit ontology, relative to the ontology directory. The plan names it
    /// or there is none: execution never probes `<id>-edit.{obo,owl,ofn,ttl}` in
    /// extension order, because that is a filename CONVENTION and a convention is
    /// exactly what a plan exists to have already resolved.
    pub edit_file: Option<String>,
    /// The repo's `owl:imports` catalog (`catalog-v001.xml`), relative to the
    /// ontology directory, or `None` when it has none.
    ///
    /// The plan NAMES the file; execution reads its contents. The resolved map is
    /// deliberately not inlined here: Protégé's Imports Wizard writes this file
    /// and curators edit it by hand, so a frozen copy would go stale silently —
    /// and it would go stale worst on a plan-only repo, which has nothing left to
    /// regenerate from. Adding an `owl:imports` and its catalog line is ordinary
    /// curation and must not require a plan regeneration.
    pub catalog_file: Option<String>,
    /// The DOSDP pattern set, enumerated at plan time. `None` means the plan
    /// makes no statement about patterns (and `om patterns` refuses); `Some` with
    /// an empty `patterns` means ingest looked and there are none.
    pub dosdp: Option<crate::spec::DosdpSpec>,
    /// The artefact-format generation this repo builds to, resolved at ingest from
    /// what the repo declares about its toolchain.
    ///
    /// It is not trivia: two behaviours that change artefact BYTES flip at 1.9.9,
    /// and both read it here rather than each deciding for itself, so a rebuilt
    /// release keeps the shape the repo's existing releases already carry.
    ///
    /// * OBO Graphs JSON nests per-element axiom-annotation `meta` from 1.9.9 —
    ///   worth two million lines across MONDO's `.json`s.
    /// * `query --update` keeps the document format's prefixes from 1.9.9; below
    ///   that boundary the update round trip drops every prefix no triple uses,
    ///   which is an `xmlns:` line in each artefact downstream of an update.
    ///
    /// Recorded rather than sniffed at write time: a plan-only repo has no build
    /// scripts or workflows left to re-read, and an ambient version would decide
    /// artefact bytes from outside the plan.
    pub emulate_robot_version: (u32, u32, u32),
    /// The ODK release this repo's outputs were made under, when the repo states
    /// one. It settles more than the tool version does — the OBO extended prefix
    /// map is baked into the image and the releases' maps differ by 388 prefixes —
    /// so where a repo names it, this is the fact the build obeys and
    /// `emulate_robot_version` follows from it. `None` for a repo that ships its
    /// own tool and names only that.
    pub emulate_odk_version: Option<(u32, u32, u32)>,
    /// `--strict`: reject structurally-broken RDF instead of repairing it while
    /// parsing. It changes WHICH AXIOMS SURVIVE A PARSE, so it is part of what
    /// this plan builds rather than a property of whoever invokes it. Resolved at
    /// ingest from the launcher flags the repo builds with.
    pub strict: bool,
    /// `-x`/`--xml-entities`: emit `&prefix;` entity references in RDF/XML. A
    /// byte-level change to every RDF/XML artefact, so likewise plan state.
    pub xml_entities: bool,
    /// The rebuild switches this plan exposes: the target groups a run may ask to
    /// rebuild rather than reuse.
    ///
    /// A repo spells these as build variables (`IMP`, `MIR`, `PAT`) whose VALUE
    /// gates whole rule sets. The value is a run input and stays out of the plan
    /// (a recorded recipe says HOW to build a target; WHETHER to build it is this
    /// run's business) — but the PARAMETER SPACE is repo configuration, and
    /// without it a plan-only repo has no way to know the switches ever existed or
    /// which targets they covered.
    pub refresh_groups: Vec<RefreshGroup>,
    /// The build-configuration variables whose value decides WHICH RULES EXIST,
    /// and the value this plan describes.
    ///
    /// A conditional is resolved once, at plan time, and the plan records the
    /// rules of the branch it selected — so the plan is a statement about one
    /// value of each. Recording that value is what lets a run say so: an
    /// assignment that agrees is a no-op, and one that disagrees is refused
    /// rather than silently building the branch the caller did not ask for.
    /// The switches the plan CAN vary are `refresh_groups`; nothing else in a
    /// plan names these, so without them a repo with no build configuration
    /// could not tell an unhonourable switch from a typo.
    pub gating_flags: std::collections::BTreeMap<String, String>,
    /// Targets declared `.PHONY` by the repo: they name no file and are always
    /// out of date. Carried so execution can apply the up-to-date rule to real
    /// file targets without ever treating a phony aggregate as satisfied.
    pub phony: Vec<String>,
    /// Paths the build writes on its way to something else and does not keep.
    ///
    /// A file the build configuration reaches only through a pattern carries one
    /// step's output to the next and goes once the chain that needed it is done;
    /// one named outright — read by another rule, or declared precious — stays.
    /// EFO's imports leave eleven ⊥-modules in the tree where a release keeps two.
    pub transient_targets: Vec<String>,
    /// Paths the build produces that no recorded rule names, because owlmake
    /// writes them from its own engines: the DOSDP pattern products and seed
    /// files, and the per-import mirrors.
    ///
    /// Without this a loaded plan cannot tell "a prerequisite this build
    /// produces" from "a prerequisite nothing can produce", and the missing-input
    /// check has to choose between failing every mirror-consuming rule and
    /// checking nothing at all. The set is derived from the repo at ingest, which
    /// makes it exactly the kind of fact the plan has to carry.
    pub native_targets: Vec<String>,
}

impl Plan {
    /// Whether `target` names a file on disk, as opposed to being a phony name
    /// that only guarantees its recipe ran.
    ///
    /// ONE answer, consulted everywhere, because this question was being answered
    /// independently in eight places with eight different predicates — which is
    /// why fixing it at one site kept failing to reach the others. Two defects
    /// came straight out of that: a `.PHONY` target materialised as a real 580 KB
    /// file by a write path that never asked, and a target reporting success while
    /// producing nothing because a different path waived the post-condition.
    ///
    /// BOTH sources are needed and neither alone is right:
    ///
    /// * the declared `phony` list is authoritative where it speaks — the repo
    ///   said so — but it carries only the names a repo declared LITERALLY, so it
    ///   never covers a pattern rule's expansions. MONDO's
    ///   `report-base-query-obsoletioncandidates-withcomment` is one: its recipe
    ///   writes `reports/report-base-$*.tsv` and nothing named after the target is
    ///   ever created, yet it appears in no `.PHONY` line.
    /// * so shape decides the rest: a name with no directory component and no
    ///   extension cannot be a filename. Anything that does look like a path must
    ///   appear, because a rule that silently produced nothing is a real failure.
    ///
    /// Replacing the shape test with the phony list would trade one silent wrong
    /// answer for another — ECTO did exactly that and broke `sparql_test`, which
    /// is phony in every practical sense and declared `.PHONY` nowhere, so the
    /// guard demanded a file it never writes. EFO declares only three `.PHONY`
    /// targets out of a 139-target surface; the list is only ever as complete as
    /// the build configuration bothered to be.
    ///
    /// This answers only whether a MISSING file is a failure. It is deliberately
    /// not the test for whether to WRITE one: a bare name can still be a real file
    /// target whose recipe ends `-o $@`, and skipping that write destroys output.
    /// See the declared-phony-only check in `run_artefact`.
    pub fn names_a_file(&self, target: &str) -> bool {
        if self.is_phony(target) {
            return false;
        }
        let t = std::path::Path::new(target);
        let bare = t.parent().is_none_or(|p| p.as_os_str().is_empty()) && t.extension().is_none();
        !bare
    }

    /// Whether `target` is declared `.PHONY`.
    ///
    /// A phony target names no file. It is always out of date however old a file
    /// sharing its name happens to be, and nothing may write a file under it —
    /// its recipe puts its output wherever the recipe says, which for a name like
    /// `component-download-hra_subset.owl` is a staging copy under `tmp/`.
    pub fn is_phony(&self, target: &str) -> bool {
        self.phony.iter().any(|p| p == target)
    }

    /// All gaps that block the requested release (imports + on-path artefacts).
    pub fn blocking_gaps(&self) -> Vec<String> {
        let mut g = Vec::new();
        for imp in &self.imports {
            for gap in &imp.gaps {
                g.push(format!("import {}: {gap}", imp.id));
            }
        }
        for gap in &self.component_gaps {
            g.push(gap.clone());
        }
        let mut any_on_path = false;
        for a in &self.artefacts {
            {
                any_on_path = true;
                if a.missing_rule {
                    g.push(format!("{}: no rule found in Makefile/override", a.target));
                }
                for gap in &a.gaps {
                    g.push(format!("{}: {gap}", a.target));
                }
            }
        }
        // A release that builds *nothing* is not "covered". When artefact
        // discovery resolves no on-path target, the loop above contributes no
        // gaps and the plan would otherwise report "✓ every step maps" over an
        // empty artefact set — a vacuous tick. This happens for repos whose own
        // rules build the release products under a build directory, as EFO's
        // `$(BUILDDIR)/efo.owl` & co. do, and declare the release set only via
        // the `release:` target's prerequisites — neither the builddir prefix nor
        // the `release:` rule is walked by discovery. Flag the empty release as a
        // hard gap.
        if !any_on_path {
            g.push(format!(
                "no release artefact discovered: the Makefile defines no rule for `{0}.owl` \
                 or any `{0}-<artefact>.owl` (release products may build under a $(BUILDDIR) \
                 subdir, or be declared only via the `release:` target's prerequisites)",
                self.id
            ));
        }
        g
    }
}

impl ImportPlan {
    /// A two-part human description of this import for the staged progress UI: a
    /// one-line headline ("Importing N terms listed in <file> from <source> using
    /// the BOT-module strategy") and a dimmed explanation of what that does.
    pub fn describe(&self, dir: &std::path::Path) -> (String, String) {
        let src = source_label(&self.source);
        let seeds = self.seed_term_files();
        let strategy = self.method();

        // Declared / pre-built module merged as-is (no pipeline).
        if self.steps.is_empty() {
            return (
                format!("Importing {} (pre-built module merged as-is)", self.id),
                String::new(),
            );
        }

        let headline = if seeds.is_empty() {
            format!("Importing {} from {src} using the {} strategy", self.id, strategy_label(strategy))
        } else {
            let n = count_seed_terms(dir, &seeds);
            format!(
                "Importing {n} terms listed in {} from {src} using the {} strategy",
                seeds.join(" + "),
                strategy_label(strategy),
            )
        };

        let mut detail = strategy_explanation(strategy).to_string();
        let extras = extra_step_labels(&self.steps);
        if !extras.is_empty() {
            if !detail.is_empty() {
                detail.push(' ');
            }
            detail.push_str(&format!("Then {}.", extras.join(", then ")));
        }
        (headline, detail)
    }
}

/// Human description of a release-artefact build stage: headline naming the
/// target and its pipeline, plus a dimmed gloss of the notable operations.
pub fn describe_artefact(a: &ArtefactPlan) -> (String, String) {
    let pipeline: Vec<&str> = a.steps.iter().filter_map(op_label).collect();
    let headline = match &a.input {
        Some(inp) => format!("Building {} from {} ({})", a.target, source_label(inp), pipeline.join(" → ")),
        None => format!("Building {} ({})", a.target, pipeline.join(" → ")),
    };
    let mut notes = Vec::new();
    for s in &a.steps {
        if let Step::Op(op) = s {
            match op {
                robot::Op::Reason { .. } => notes.push(
                    "reasoning classifies the ontology and asserts the inferred subsumptions",
                ),
                robot::Op::Relax { .. } => notes.push(
                    "relax rewrites equivalence axioms into the weaker existential subclass form OBO tools expect",
                ),
                robot::Op::Reduce { .. } => notes.push(
                    "reduce removes redundant subclass axioms entailed by transitivity",
                ),
                _ => {}
            }
        }
    }
    notes.dedup();
    (headline, notes.join("; "))
}

/// The trailing basename of a source URL/path (`…/uberon.owl` → `uberon.owl`).
fn source_label(s: &str) -> String {
    s.rsplit(['/', '\\']).next().unwrap_or(s).to_string()
}

/// Count the (de-duplicated) seed terms across `files`, read relative to the repo.
fn count_seed_terms(dir: &std::path::Path, files: &[String]) -> usize {
    let mut seen = std::collections::HashSet::new();
    for f in files {
        for line in std::fs::read_to_string(dir.join(f)).unwrap_or_default().lines() {
            let t = line.trim().trim_start_matches('<').trim_end_matches('>').trim();
            if !t.is_empty() && !t.starts_with('#') {
                seen.insert(t.to_string());
            }
        }
    }
    seen.len()
}

/// Display name for an extraction strategy token.
fn strategy_label(method: &str) -> String {
    match method.to_ascii_uppercase().as_str() {
        "BOT" => "BOT-module".into(),
        "TOP" => "TOP-module".into(),
        "STAR" => "STAR-module".into(),
        "MIREOT" => "MIREOT".into(),
        "FILTER" => "signature-filter".into(),
        "COPY" => "whole-ontology".into(),
        other => other.to_string(),
    }
}

/// One-sentence explanation of what an extraction strategy produces.
fn strategy_explanation(method: &str) -> &'static str {
    match method.to_ascii_uppercase().as_str() {
        "BOT" => "A BOT (bottom, ⊥) syntactic-locality module is the smallest subset of \
            the source ontology that preserves every entailment about the seed terms — \
            it keeps each seed term together with its superclasses and the axioms relating \
            them, while dropping unrelated branches.",
        "TOP" => "A TOP (top, ⊤) locality module keeps the seed terms together with their \
            subclasses, preserving entailments in the downward direction.",
        "STAR" => "A STAR locality module is the smallest module that preserves all \
            entailments over the seed signature in both directions.",
        "MIREOT" => "MIREOT copies the seed terms and a minimal set of their ancestors \
            without the logical-completeness guarantee of a locality module.",
        "FILTER" => "A signature filter keeps only the axioms whose terms all lie within \
            the seed signature — the module is the seed slice of the source.",
        _ => "",
    }
}

/// Labels for the non-extraction steps of an import pipeline (for the detail line).
fn extra_step_labels(steps: &[Step]) -> Vec<String> {
    let mut out = Vec::new();
    for s in steps {
        let label = match s {
            Step::Op(robot::Op::Remove(spec)) if !spec.term_files.is_empty() => {
                format!("remove the terms in {}", spec.term_files.join(", "))
            }
            Step::Op(robot::Op::Remove(_)) => "remove the selected axioms".to_string(),
            Step::Op(robot::Op::Rename { mappings: Some(m), .. }) => {
                format!("rename entities via {}", source_label(m))
            }
            Step::Op(robot::Op::Rename { .. }) => "rename entities".to_string(),
            Step::Op(robot::Op::Filter(_)) => "filter to the seed signature".to_string(),
            Step::Branch { condition, .. } => {
                format!("conditionally (if {})", condition.describe())
            }
            Step::Shell { .. } | Step::Jq(_) | Step::Sssom(_) => {
                "run a dynamic step (shell)".to_string()
            }
            _ => continue,
        };
        if !out.contains(&label) {
            out.push(label);
        }
    }
    out
}

/// Short verb label for an artefact pipeline op (for the headline summary).
fn op_label(s: &Step) -> Option<&'static str> {
    match s {
        Step::Op(op) => Some(match op {
            robot::Op::Merge { .. } => "merge",
            robot::Op::Unmerge { .. } => "unmerge",
            robot::Op::Reason { .. } => "reason",
            robot::Op::Relax { .. } => "relax",
            robot::Op::Reduce { .. } => "reduce",
            robot::Op::Materialize { .. } => "materialize",
            robot::Op::Remove(_) => "remove",
            robot::Op::Filter(_) => "filter",
            robot::Op::Annotate(_) => "annotate",
            robot::Op::Convert { .. } => "convert",
            robot::Op::Query { .. } => "query",
            robot::Op::Rename { .. } => "rename",
            robot::Op::Extract { .. } => "extract",
            robot::Op::Template { .. } => "template",
            _ => "process",
        }),
        Step::Shell { .. } | Step::Jq(_) | Step::Sssom(_) => Some("shell"),
        Step::Branch { .. } => Some("if"),
        _ => None,
    }
}

impl fmt::Display for Plan {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        writeln!(f, "╔═ owlmake ODK release plan ═══════════════════════════════════════")?;
        writeln!(f, "║ ontology       : {}", self.id)?;
        writeln!(f, "║ ontology IRI   : {}", self.ontology_iri)?;
        writeln!(f, "║ version        : {}", self.version)?;
        writeln!(f, "║ reasoner       : {}", self.reasoner)?;
        writeln!(f, "╠─ imports ({}){}", self.imports.len(),
            if self.use_base_merging { ", base-merging" } else { "" })?;
        for imp in &self.imports {
            let status = if imp.cached { "cached" } else { "DOWNLOAD" };
            writeln!(f, "║   {:<12} {:<8} [{}] {}", imp.id, imp.method(), status, imp.source)?;
            let seeds = imp.seed_term_files();
            if !seeds.is_empty() {
                writeln!(f, "║       seed: {}", seeds.join(", "))?;
            }
            let extra: Vec<&str> = imp
                .steps
                .iter()
                .filter_map(|s| match s {
                    Step::Op(robot::Op::Remove(_)) => Some("remove"),
                    Step::Op(robot::Op::Rename { .. }) => Some("rename"),
                    Step::Shell { .. } | Step::Jq(_) | Step::Sssom(_) => Some("shell"),
                    _ => None,
                })
                .collect();
            if !extra.is_empty() {
                writeln!(f, "║       steps: {}", extra.join(" → "))?;
            }
            for g in &imp.gaps {
                writeln!(f, "║       ⚠ {g}")?;
            }
        }
        if let Some(m) = &self.merged_import {
            writeln!(f, "║   → merged into {m}")?;
        }
        if !self.exclude_iri_patterns.is_empty() {
            writeln!(f, "║   exclusions  : {} IRI pattern(s)", self.exclude_iri_patterns.len())?;
        }
        if !self.components.is_empty() {
            writeln!(f, "╠─ components")?;
            for c in &self.components {
                let blocked = self.component_gaps.iter().any(|g| g.starts_with(&format!("component {c}:")));
                writeln!(f, "║   [{}] {c}", if blocked { "✗" } else { "✓" })?;
            }
            for g in &self.component_gaps {
                writeln!(f, "║     - {g}")?;
            }
        }
        writeln!(f, "╠─ artefacts")?;
        for a in &self.artefacts {
            let mark = if a.missing_rule {
                "?"
            } else if a.gaps.is_empty() {
                "✓"
            } else {
                "✗"
            };
            writeln!(f, "║ [{mark}] {}{}", a.target,
                a.input.as_ref().map(|i| format!("   ⟵ {i}")).unwrap_or_default())?;
            if a.missing_rule {
                writeln!(f, "║       (no rule found in Makefile/override)")?;
                continue;
            }
            for s in &a.steps {
                let bullet = match s {
                    Step::Op(_) => "•",
                    Step::File(_) | Step::Jq(_) | Step::Sssom(_) => "◦",
                    Step::Inert(_) => "·",
                    Step::Shell { .. } => "›",
                    // Covered, but run by invoking owlmake's own subcommand rather
                    // than threaded through the pipeline — not a gap, so not `✗`.
                    Step::CliRobot { .. } => "▪",
                    _ => "✗",
                };
                writeln!(f, "║       {bullet} {}", s.label())?;
            }
        }
        let gaps = self.blocking_gaps();
        writeln!(f, "╠─ coverage")?;
        // Tools the build shells out to that owlmake neither bundles nor knows.
        // The steps run, so this is not a gap — but they run only where the tool
        // exists, and a build is easier to preflight than to debug: `git` is not
        // in owlmake's own container image, and four of EFO's targets need it.
        let mut needs: Vec<&str> = self
            .artefacts
            .iter()
            .chain(self.prerequisites.iter())
            .flat_map(|a| a.steps.iter())
            .flat_map(|s| match s {
                Step::Shell { requires, .. } => requires.as_slice(),
                _ => &[],
            })
            .map(String::as_str)
            .collect();
        needs.sort_unstable();
        needs.dedup();
        if !needs.is_empty() {
            writeln!(f, "║   ! needs on PATH: {}", needs.join(", "))?;
        }
        // Prerequisites are reported separately from the release path. One with
        // an unmappable step is not fatal *if* its output is already on disk —
        // but the committed copy is then consumed as-is and cannot be
        // regenerated, so a stale one would go unnoticed. Say that out loud
        // rather than let the coverage tick imply the file is reproducible.
        let stale: Vec<(&str, Vec<String>)> = self
            .prerequisites
            .iter()
            .map(|p| {
                (p.target.as_str(), p.steps.iter().flat_map(|s| s.unrunnable_gaps()).collect::<Vec<_>>())
            })
            .filter(|(_, g)| !g.is_empty())
            .collect();
        if !stale.is_empty() {
            writeln!(f, "║   ! {} prerequisite(s) owlmake cannot rebuild:", stale.len())?;
            for (target, why) in &stale {
                writeln!(f, "║     - {target}: {}", why.join("; "))?;
            }
            writeln!(f, "║       (the committed copy is used as-is; it will not be refreshed)")?;
        }
        if gaps.is_empty() {
            writeln!(f, "║   ✓ every step on the release path maps to owlmake")?;
        } else {
            writeln!(f, "║   ✗ {} uncovered step(s) on the release path:", gaps.len())?;
            for g in &gaps {
                writeln!(f, "║     - {g}")?;
            }
        }
        write!(f, "╚══════════════════════════════════════════════════════════════════")
    }
}
